"""Strategy Factory skeleton for no-trade / compile-only pipeline planning."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import json


SAFETY_NOTICE = "Inventory only; no MT5 run; no trading authorization."


@dataclass(frozen=True)
class StrategyVariantSpec:
    strategy_type: str
    variant_id: str
    parameters: dict[str, object] = field(default_factory=dict)

    def to_set_lines(self) -> list[str]:
        lines = []
        for key in sorted(self.parameters):
            value = self.parameters[key]
            if isinstance(value, bool):
                rendered = "true" if value else "false"
            else:
                rendered = str(value)
            lines.append(f"{key}={rendered}")
        return lines


class StrategyFactory:
    """Generate strategy variant specs from a parameter-space schema."""

    def __init__(self, schema_path: str | Path):
        self.schema_path = Path(schema_path)
        self.schema = self._load_schema(self.schema_path)

    @staticmethod
    def _load_schema(path: Path) -> dict:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if "strategyTypes" not in payload:
            raise ValueError("schema missing strategyTypes")
        return payload

    def list_strategy_types(self) -> list[str]:
        return sorted(self.schema["strategyTypes"].keys())

    def build_variants(self, strategy_type: str, *, limit: int | None = None) -> list[StrategyVariantSpec]:
        if strategy_type not in self.schema["strategyTypes"]:
            raise ValueError(f"unknown strategy type: {strategy_type}")

        definition = self.schema["strategyTypes"][strategy_type]
        base_parameters = dict(definition.get("baseParameters", {}))
        base_parameters.setdefault("InpEnableTrading", False)
        base_parameters.setdefault("InpEnableRiskObservation", True)

        variants: list[StrategyVariantSpec] = []
        for index, override in enumerate(definition.get("variants", []), start=1):
            parameters = dict(base_parameters)
            parameters.update(override.get("parameters", {}))
            variants.append(
                StrategyVariantSpec(
                    strategy_type=strategy_type,
                    variant_id=override.get("variantId", f"v{index:03d}"),
                    parameters=parameters,
                )
            )
            if limit is not None and len(variants) >= limit:
                break
        return variants

    def render_set_preview(self, variant: StrategyVariantSpec) -> str:
        header = [
            f"; generated by StrategyFactory ({SAFETY_NOTICE})",
            f"; strategy_type={variant.strategy_type}",
            f"; variant_id={variant.variant_id}",
            "",
        ]
        return "\n".join(header + variant.to_set_lines()) + "\n"