'use client';

import { useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';

export default function DisclaimerPage() {
  const router = useRouter();
  const [lang, setLang] = useState<'EN' | 'CN'>('EN');

  const t = useMemo(() => ({
    back: lang === 'EN' ? '← Back to Home' : '← 返回首页',
    title: lang === 'EN' ? 'Disclaimer' : '免责声明',
    lastUpdated: lang === 'EN' ? 'Last updated: June 2026' : '最后更新：2026年6月',
    intro: lang === 'EN'
      ? 'This Disclaimer applies to all content and services provided by FateMatrices. By using our Service, you acknowledge that you have read, understood, and agree to this Disclaimer.'
      : '本免责声明适用于 FateMatrices 提供的所有内容和服务。使用我们的服务即表示您已阅读、理解并同意本免责声明。',
    sections: [
      {
        heading: lang === 'EN' ? '1. Entertainment Purpose Only' : '1. 仅供娱乐用途',
        body: lang === 'EN'
          ? 'All reports, interpretations, and content generated by FateMatrices are provided for entertainment and personal insight purposes only. They do not constitute, and should not be interpreted as, financial, legal, medical, investment, psychological, or any other form of professional advice.'
          : 'FateMatrices 生成的所有报告、解读和内容仅供娱乐和个人参考用途。不构成也不应被解释为财务、法律、医疗、投资、心理或任何其他形式的专业建议。',
      },
      {
        heading: lang === 'EN' ? '2. No Guarantees or Predictions' : '2. 无保证或预测',
        body: lang === 'EN'
          ? 'FateMatrices makes no guarantees, warranties, or representations regarding the accuracy, completeness, or reliability of any report content. No outcomes in your life, career, relationships, health, or finances are guaranteed or predicted by our Service.'
          : 'FateMatrices 不对任何报告内容的准确性、完整性或可靠性作出任何保证、担保或陈述。我们的服务不保证或预测您的生活、职业、关系、健康或财务的任何结果。',
      },
      {
        heading: lang === 'EN' ? '3. User Responsibility' : '3. 用户责任',
        body: lang === 'EN'
          ? 'You acknowledge that any decisions, actions, or inactions you take based on the content provided by FateMatrices are your sole responsibility. FateMatrices shall not be liable for any consequences arising from your reliance on our reports or services.'
          : '您确认，您基于 FateMatrices 提供的内容所做的任何决定、行动或不行动均由您自行承担责任。FateMatrices 不对您依赖我们的报告或服务而产生的任何后果承担责任。',
      },
      {
        heading: lang === 'EN' ? '4. Not a Substitute for Professional Advice' : '4. 不能替代专业建议',
        body: lang === 'EN'
          ? 'If you have concerns regarding your financial, legal, medical, or mental health situation, you should consult a qualified professional. FateMatrices is not a substitute for professional advice, diagnosis, or treatment.'
          : '如果您对财务、法律、医疗或心理健康状况有疑虑，您应咨询合格的专业人士。FateMatrices 不能替代专业建议、诊断或治疗。',
      },
      {
        heading: lang === 'EN' ? '5. AI-Generated Content' : '5. AI 生成内容',
        body: lang === 'EN'
          ? 'Reports are generated by artificial intelligence based on the information you provide. AI-generated content may contain errors, inaccuracies, or biases. FateMatrices does not warrant the correctness of AI-generated interpretations.'
          : '报告由人工智能根据您提供的信息生成。AI 生成的内容可能包含错误、不准确或偏见。FateMatrices 不保证 AI 生成解读的正确性。',
      },
      {
        heading: lang === 'EN' ? '6. External Links & Third Parties' : '6. 外部链接与第三方',
        body: lang === 'EN'
          ? 'Our Service may contain links to third-party websites or services. FateMatrices is not responsible for the content, privacy policies, or practices of any third-party sites. Your use of third-party services is at your own risk.'
          : '我们的服务可能包含指向第三方网站或服务的链接。FateMatrices 不对任何第三方网站的内容、隐私政策或做法负责。您使用第三方服务需自行承担风险。',
      },
      {
        heading: lang === 'EN' ? '7. Limitation of Liability' : '7. 责任限制',
        body: lang === 'EN'
          ? 'To the maximum extent permitted by applicable law, FateMatrices and its operators shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service.'
          : '在适用法律允许的最大范围内，FateMatrices 及其运营者不对因您使用本服务而产生或与之相关的任何直接、间接、附带、特殊、后果性或惩罚性损害承担责任。',
      },
      {
        heading: lang === 'EN' ? '8. Changes to Disclaimer' : '8. 免责声明修改',
        body: lang === 'EN'
          ? 'We reserve the right to modify this Disclaimer at any time. Changes will be posted on this page with an updated date. Your continued use of the Service constitutes acceptance of the modified Disclaimer.'
          : '我们保留随时修改本免责声明的权利。修改内容将发布在本页面并注明更新日期。您继续使用本服务即表示接受修改后的免责声明。',
      },
      {
        heading: lang === 'EN' ? '9. Contact' : '9. 联系方式',
        body: lang === 'EN'
          ? 'For questions about this Disclaimer, please contact us at: support@fatematrices.com'
          : '如有关于本免责声明的问题，请联系：support@fatematrices.com',
      },
    ],
  }), [lang]);

  return (
    <div className="min-h-screen bg-[#030712] text-white">
      <header className="flex items-center justify-between p-4 md:p-6 border-b border-gray-800/50">
        <button
          onClick={() => router.push('/')}
          className="text-cyan-400 hover:text-cyan-300 text-sm font-mono uppercase tracking-wider transition-colors"
        >
          {t.back}
        </button>
        <div className="flex gap-2">
          <button
            onClick={() => setLang('EN')}
            className={`px-3 py-1 rounded-lg text-xs uppercase tracking-wider transition-all ${
              lang === 'EN' ? 'bg-cyan-500 text-black font-bold' : 'text-gray-400 hover:text-white'
            }`}
          >
            EN
          </button>
          <button
            onClick={() => setLang('CN')}
            className={`px-3 py-1 rounded-lg text-xs uppercase tracking-wider transition-all ${
              lang === 'CN' ? 'bg-cyan-500 text-black font-bold' : 'text-gray-400 hover:text-white'
            }`}
          >
            中文
          </button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 md:px-8 py-12 md:py-20">
        <h1 className="text-3xl md:text-5xl font-black uppercase tracking-tighter mb-2 text-white">
          {t.title}
        </h1>
        <p className="text-gray-500 text-xs uppercase tracking-[0.3em] font-mono mb-10 md:mb-16">
          {t.lastUpdated}
        </p>

        <p className="text-gray-300 text-sm md:text-base leading-relaxed mb-10 md:mb-16">
          {t.intro}
        </p>

        <div className="space-y-10 md:space-y-14">
          {t.sections.map((section, i) => (
            <section key={i}>
              <h2 className="text-lg md:text-xl font-bold text-cyan-400 mb-3 md:mb-4 uppercase tracking-wide">
                {section.heading}
              </h2>
              <p className="text-gray-300 text-sm md:text-base leading-relaxed">
                {section.body}
              </p>
            </section>
          ))}
        </div>
      </main>

      <footer className="border-t border-gray-800/50 py-8 text-center">
        <p className="text-gray-600 text-xs uppercase tracking-[0.3em] font-mono">
          FateMatrices © 2026
        </p>
      </footer>
    </div>
  );
}
