//+------------------------------------------------------------------+
//|                                WallStreet_Sniper_V6_Ultimate.mq5 |
//|                                  Generated by AI Quant Architect |
//|                    Version 6.0 - 终极性能优化版 (根除实盘卡顿隐患) |
//+------------------------------------------------------------------+
#property copyright "AI Quant Architect"
#property version   "6.00"
#property description "WallStreet_Sniper - 工业级区间突破量化EA"
#property description "已集成：时间悖论修复、黑匣子监控、循环外提权性能优化"

#include <Trade\Trade.mqh>

//+------------------------------------------------------------------+
//| 输入参数                                                         |
//+------------------------------------------------------------------+

//--- 【核心风控模块】
input group "========== 核心风控模块 =========="
input int      Magic_Number         = 888888;           // 魔术数字
input double   Risk_Percentage      = 1.0;              // 动态手数风险百分比（上限强制2.0%）
input double   Min_Expectancy_Rate  = 0.2;              // 系统最低期望值阈值
input int      Max_Continuous_Loss  = 3;                // 日内最大连续亏损次数熔断阈值
input double   Max_Daily_Drawdown   = 5.0;              // 日内账户最大回撤百分比熔断阈值
input double   Max_Single_Loss_Rate = 2.0;              // 极端行情下单笔最大允许亏损百分比应急防线

//--- 【复合信号提取模块】
input group "========== 复合信号提取模块 =========="
input int      BreakoutPeriod       = 20;               // 突破区间K线数量
input int      Trend_Filter_EMA     = 200;              // 宏观多空分界的EMA周期
input bool     Enable_Entity_Break  = false;            // 是否仅允许实体突破(实盘建议false防假死)
input int      ADXPeriod            = 14;               // ADX计算周期
input double   ADXThreshold         = 25.0;             // ADX动能确认阈值(回测排查可设为0)
input int      GMT_Offset           = 0;                // 服务器时区偏移（北京时间=8，EET=2/3）
input int      TradingStartHour     = 15;               // 允许开仓的目标时区时间（回测排查可设0）
input int      TradingEndHour       = 20;               // 允许开仓的目标时区时间（回测排查可设24）

//--- 【动态出场与保本模块】
input group "========== 动态出场与保本模块 =========="
input int      ATRPeriod            = 14;               // 波动率计算周期
input double   ATRMultiplier        = 2.0;              // 初始止损距离乘数
input bool     Enable_Break_Even    = true;             // 启用智能保本
input int      Break_Even_Slippage  = 5;                // 保本触发时附加滑点保护费(微点)
input bool     Enable_Trailing_Stop = true;             // 启用ATR动态追踪止盈
input double   TrailingATRMultiplier= 1.5;              // 追踪止盈ATR乘数

//--- 【恶劣环境过滤模块】
input group "========== 恶劣环境过滤模块 =========="
input int      MaxSpread            = 50;               // 开仓前允许的最大点差(回测若不开仓可放宽至500)
input bool     Enable_Weekend_Close = true;             // 周五收盘前强制平仓
input bool     Enable_News_Filter   = true;             // 启用高重要性新闻定时过滤

//--- 【推送通知模块】
input group "========== 推送通知模块 =========="
input bool     Enable_Push          = true;             // 启用推送通知
input bool     Enable_Daily_Report  = true;             // 启用每日统计报告

//+------------------------------------------------------------------+
//| 全局变量                                                         |
//+------------------------------------------------------------------+
CTrade         Trade;
int            handle_ATR, handle_EMA, handle_ADX;
double         g_current_atr;                            
int            daily_loss_count;
double         daily_start_equity;
datetime       daily_reset_time;
double         cumulative_expectancy;
datetime       g_last_news_check_time;                   
bool           g_news_lock_flag;                         
bool           g_system_sleep;                           
datetime       g_last_report_time, g_last_bar_time;                          
int            g_daily_trades;                           
double         g_daily_pnl, g_total_win_amount, g_total_loss_amount;                       
int            g_total_win, g_total_loss, g_last_expectancy_deals;                  

//+------------------------------------------------------------------+
//| 专家初始化函数                                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   Trade.SetExpertMagicNumber(Magic_Number);
   Trade.SetDeviationInPoints(10);                       

   handle_ATR = iATR(_Symbol, PERIOD_CURRENT, ATRPeriod);
   handle_EMA = iMA(_Symbol, PERIOD_CURRENT, Trend_Filter_EMA, 0, MODE_EMA, PRICE_CLOSE);
   handle_ADX = iADX(_Symbol, PERIOD_CURRENT, ADXPeriod);

   if(handle_ATR == INVALID_HANDLE || handle_EMA == INVALID_HANDLE || handle_ADX == INVALID_HANDLE)
   {
      Print("🔴 指标初始化失败！"); return INIT_FAILED;
   }

   daily_start_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   Print("🟢 WallStreet_Sniper V6 Ultimate 部署成功！性能刺客已清除！");
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
   IndicatorRelease(handle_ATR); IndicatorRelease(handle_EMA); IndicatorRelease(handle_ADX);
}

//+------------------------------------------------------------------+
//| 核心工具函数                                                     |
//+------------------------------------------------------------------+
int GetTargetHour()
{
   MqlDateTime dt; TimeCurrent(dt);
   return ((dt.hour + GMT_Offset) % 24 + 24) % 24; 
}

bool IsNewBar()
{
   datetime current_bar_time = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(current_bar_time == 0) return false;
   if(g_last_bar_time != current_bar_time)
   {
      g_last_bar_time = current_bar_time;
      return true;
   }
   return false;
}

string GetLastErrorDescription(int error_code)
{
   switch(error_code)
   {
      case TRADE_RETCODE_REQUOTE:                 return "重新报价";
      case TRADE_RETCODE_INVALID_STOPS:           return "无效止损/止盈位";
      case TRADE_RETCODE_INVALID_PRICE:           return "无效价格";
      case TRADE_RETCODE_TIMEOUT:                 return "交易超时";
      case TRADE_RETCODE_PRICE_CHANGED:           return "价格已变动";
      case TRADE_RETCODE_NO_MONEY:                return "资金不足";
      default:                                    return "错误码(" + (string)error_code + ")";
   }
}

void PushNotification(string message)
{
   if(Enable_Push && !SendNotification(message)) Print("推送失败: ", GetLastError());
}

void SendDailyReport()
{
   if(!Enable_Push || !Enable_Daily_Report) return;
   int target_hour = GetTargetHour();
   MqlDateTime dt; TimeCurrent(dt);

   if(dt.min == 0 && (target_hour == 12 || target_hour == 22))
   {
      if(TimeCurrent() - g_last_report_time >= 3600) 
      {
         g_last_report_time = TimeCurrent();
         double equity = AccountInfoDouble(ACCOUNT_EQUITY);
         double drawdown = (daily_start_equity > 0.0) ? (daily_start_equity - equity) / daily_start_equity * 100.0 : 0;
         string period = (target_hour == 12) ? "午间" : "晚间";
         string report = StringFormat("【狙击手 %s报告(%d:00)】\n净值: %.2f\n持仓: %d\n成交: %d笔\n日内盈亏: %.2f\n回撤: %.2f%%\n期望值: %.2f",
                                      period, target_hour, equity, PositionsTotal(), g_daily_trades, g_daily_pnl, drawdown, cumulative_expectancy);
         PushNotification(report);
      }
   }
}

//+------------------------------------------------------------------+
//| 核心风控推演函数                                                 |
//+------------------------------------------------------------------+
double CalculateSafeLotSize(double sl_points)
{
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double actual_risk_pct = fmin(Risk_Percentage, 2.0);
   double risk_amount = equity * (actual_risk_pct / 100.0);
   
   double tick_value = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tick_size = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);

   if(tick_value <= 0 || sl_points <= 0) return 0.0;
   double loss_per_lot = (sl_points * point / tick_size) * tick_value;
   if(loss_per_lot <= 0) return 0.0;

   double raw_lot = risk_amount / loss_per_lot;
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   raw_lot = MathFloor(raw_lot / step) * step;

   return fmax(SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN), fmin(raw_lot, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX)));
}

bool CheckRiskRewardRatio(double entry, double sl, double tp)
{
   double risk = MathAbs(entry - sl), reward = MathAbs(tp - entry);
   return (risk > 0 && (reward / risk) >= 2.95); 
}

//+------------------------------------------------------------------+
//| 智能保本与追踪雷达                                               |
//+------------------------------------------------------------------+
void CheckBreakEvenAndTrailing()
{
   if(!Enable_Break_Even && !Enable_Trailing_Stop) return;
   if(g_current_atr <= 0.0) return;
   
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   
   // 🚨 【V6性能优化核心】：将底层API请求彻底移出订单遍历循环！
   long stops_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) != _Symbol || PositionGetInteger(POSITION_MAGIC) != Magic_Number) continue;

      double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
      double current_sl = PositionGetDouble(POSITION_SL);
      double current_tp = PositionGetDouble(POSITION_TP);
      long type = PositionGetInteger(POSITION_TYPE);
      double current_price = (type == POSITION_TYPE_BUY) ? SymbolInfoDouble(_Symbol, SYMBOL_BID) : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double profit_dist = MathAbs(current_price - open_price);

      if(profit_dist < g_current_atr) continue; 
      double be_sl = (type == POSITION_TYPE_BUY) ? open_price + Break_Even_Slippage * point : open_price - Break_Even_Slippage * point;

      // 1. 保本移动
      if(Enable_Break_Even)
      {
         bool need_be = (type == POSITION_TYPE_BUY) ? (current_sl < be_sl && current_price > be_sl) : (current_sl > be_sl && current_price < be_sl);
         if(need_be && Trade.PositionModify(ticket, be_sl, current_tp)) current_sl = be_sl;
      }

      // 2. 追踪止盈
      if(Enable_Trailing_Stop)
      {
         bool is_be_protected = (type == POSITION_TYPE_BUY) ? (current_sl >= be_sl - point) : (current_sl <= be_sl + point);
         if(!is_be_protected || MathAbs(current_price - be_sl) < g_current_atr * 0.5) continue;

         double trailing_dist = g_current_atr * TrailingATRMultiplier;
         double new_trailing_sl = (type == POSITION_TYPE_BUY) ? current_price - trailing_dist : current_price + trailing_dist;

         // StopsLevel 贴边防护 (直接使用循环外部获取的 stops_level 变量)
         if(stops_level > 0 && MathAbs(current_price - new_trailing_sl) < stops_level * point)
         {
            new_trailing_sl = (type == POSITION_TYPE_BUY) ? current_price - stops_level * point : current_price + stops_level * point;
         }

         if((type == POSITION_TYPE_BUY && new_trailing_sl < be_sl) || (type == POSITION_TYPE_SELL && new_trailing_sl > be_sl)) new_trailing_sl = be_sl;

         bool need_trail = (type == POSITION_TYPE_BUY) ? (new_trailing_sl > current_sl) : (new_trailing_sl < current_sl);
         if(need_trail) Trade.PositionModify(ticket, new_trailing_sl, current_tp);
      }
   }
}

//+------------------------------------------------------------------+
//| 环境与过滤                                                       |
//+------------------------------------------------------------------+
bool IsEnvironmentSafe()
{
   if(SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) > MaxSpread) 
   {
      // Print("⚠️ 黑匣子: 点差过大拦截!");
      return false;
   }
   
   double req_margin = 0;
   double check_lot = fmax(CalculateSafeLotSize(100), SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
   if(OrderCalcMargin(ORDER_TYPE_BUY, _Symbol, check_lot, SymbolInfoDouble(_Symbol, SYMBOL_ASK), req_margin))
   {
      if(AccountInfoDouble(ACCOUNT_MARGIN_FREE) < req_margin * 1.2) return false;
   }
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == Magic_Number) return false;
   }
   if(Enable_News_Filter && g_news_lock_flag) return false;
   return true;
}

void CheckHighImpactNews()
{
   if(!Enable_News_Filter || TimeCurrent() - g_last_news_check_time < 60) return;
   g_last_news_check_time = TimeCurrent();
   MqlDateTime dt; TimeCurrent(dt);
   bool in_news_zone = false;
   if(dt.day_of_week >= 1 && dt.day_of_week <= 5)
   {
      int total_min = dt.hour * 60 + dt.min;
      if((total_min >= 495 && total_min <= 525) || (total_min >= 795 && total_min <= 825) || (total_min >= 1330 && total_min <= 1360)) in_news_zone = true;
   }
   g_news_lock_flag = in_news_zone;
}

//+------------------------------------------------------------------+
//| 动能信号提取                                                     |
//+------------------------------------------------------------------+
int CheckEntrySignal(double &current_atr)
{
   current_atr = 0.0;
   double atr_arr[], ema_arr[], adx_arr[];
   if(CopyBuffer(handle_ATR, 0, 1, 1, atr_arr) < 1 || CopyBuffer(handle_EMA, 0, 1, 1, ema_arr) < 1 || CopyBuffer(handle_ADX, 0, 1, 1, adx_arr) < 1) return 0;
   
   current_atr = atr_arr[0];
   if(current_atr <= 0 || adx_arr[0] < ADXThreshold) return 0;

   int target_hour = GetTargetHour();
   if(target_hour < TradingStartHour || target_hour >= TradingEndHour) return 0;

   // 🚨 核心修复：寻找极值必须跳过刚刚闭合的破局K线！从索引 2 开始寻找！
   int highest_idx = iHighest(_Symbol, PERIOD_CURRENT, MODE_HIGH, BreakoutPeriod, 2);
   int lowest_idx = iLowest(_Symbol, PERIOD_CURRENT, MODE_LOW, BreakoutPeriod, 2);
   if(highest_idx < 0 || lowest_idx < 0) return 0;

   double highest_high = iHigh(_Symbol, PERIOD_CURRENT, highest_idx);
   double lowest_low = iLow(_Symbol, PERIOD_CURRENT, lowest_idx);
   double last_close = iClose(_Symbol, PERIOD_CURRENT, 1);
   double last_open = iOpen(_Symbol, PERIOD_CURRENT, 1);

   if(last_close > highest_high && last_close > ema_arr[0] && (!Enable_Entity_Break || last_open > highest_high)) return 1;
   if(last_close < lowest_low && last_close < ema_arr[0] && (!Enable_Entity_Break || last_open < lowest_low)) return -1;
   return 0;
}

//+------------------------------------------------------------------+
//| 全局熔断与单笔斩首                                               |
//+------------------------------------------------------------------+
void CloseAllPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong tkt = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == Magic_Number) Trade.PositionClose(tkt);
   }
}

bool CheckDailyFuse()
{
   MqlDateTime dt; TimeCurrent(dt);
   datetime today = StructToTime(dt) - (dt.hour * 3600 + dt.min * 60 + dt.sec);
   if(daily_reset_time != today)
   {
      daily_reset_time = today; daily_start_equity = AccountInfoDouble(ACCOUNT_EQUITY); daily_loss_count = 0;
   }
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double drawdown = (daily_start_equity > 0) ? (daily_start_equity - equity) / daily_start_equity * 100.0 : 0;

   if(drawdown >= Max_Daily_Drawdown || daily_loss_count >= Max_Continuous_Loss)
   {
      CloseAllPositions(); return true;
   }
   if(Enable_Weekend_Close && dt.day_of_week == 5 && dt.hour >= 18 && PositionsTotal() > 0)
   {
      CloseAllPositions(); return true;
   }
   return false;
}

void CheckExtremeLoss()
{
   double base_eq = (daily_start_equity > 0) ? daily_start_equity : AccountInfoDouble(ACCOUNT_EQUITY);
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong tkt = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == Magic_Number)
      {
         double pnl = PositionGetDouble(POSITION_PROFIT);
         if(pnl < 0 && base_eq > 0 && (MathAbs(pnl) / base_eq * 100.0) >= Max_Single_Loss_Rate)
         {
            if(Trade.PositionClose(tkt)) daily_loss_count++;
         }
      }
   }
}

//+------------------------------------------------------------------+
//| 增量期望值更新与交易事件监听                                     |
//+------------------------------------------------------------------+
void UpdateExpectancy()
{
   int total_deals = g_total_win + g_total_loss;
   if(total_deals <= g_last_expectancy_deals || total_deals < 10) return;
   g_last_expectancy_deals = total_deals;

   double win_rate = (double)g_total_win / total_deals;
   double avg_win = (g_total_win > 0) ? g_total_win_amount / g_total_win : 0;
   double avg_loss = (g_total_loss > 0) ? MathAbs(g_total_loss_amount) / g_total_loss : 0;

   cumulative_expectancy = (avg_loss > 0) ? (win_rate * avg_win) - ((1.0 - win_rate) * avg_loss) : (g_total_win_amount + g_total_loss_amount) / total_deals;
   g_system_sleep = (cumulative_expectancy < Min_Expectancy_Rate);
}

void OnTradeTransaction(const MqlTradeTransaction &trans, const MqlTradeRequest &request, const MqlTradeResult &result)
{
   if(trans.type != TRADE_TRANSACTION_DEAL_ADD) return;
   ulong tkt = trans.deal;
   if(tkt == 0 || HistoryDealGetInteger(tkt, DEAL_MAGIC) != Magic_Number || HistoryDealGetString(tkt, DEAL_SYMBOL) != _Symbol) return;
   if(HistoryDealGetInteger(tkt, DEAL_ENTRY) != DEAL_ENTRY_OUT) return; 

   double profit = HistoryDealGetDouble(tkt, DEAL_PROFIT);
   g_daily_trades++; g_daily_pnl += profit;

   if(profit > 0) { g_total_win_amount += profit; g_total_win++; }
   else if(profit < 0) { g_total_loss_amount += profit; g_total_loss++; }
   UpdateExpectancy();
}

//+------------------------------------------------------------------+
//| 系统主循环 (OnTick)                                              |
//+------------------------------------------------------------------+
void OnTick()
{
   SendDailyReport();
   if(CheckDailyFuse()) return;
   CheckHighImpactNews();

   CheckBreakEvenAndTrailing();
   CheckExtremeLoss();

   if(g_system_sleep || !IsEnvironmentSafe() || !IsNewBar()) return;
   if(BarsCalculated(handle_ATR) < BreakoutPeriod || BarsCalculated(handle_EMA) < BreakoutPeriod || BarsCalculated(handle_ADX) < BreakoutPeriod) return;

   double current_atr = 0.0;
   int signal = CheckEntrySignal(current_atr);
   if(current_atr > 0) g_current_atr = current_atr;
   if(signal == 0) return;

   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double entry = (signal == 1) ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double spread_cost = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * point;

   double sl = (signal == 1) ? entry - current_atr * ATRMultiplier - spread_cost : entry + current_atr * ATRMultiplier + spread_cost;
   double tp = (signal == 1) ? entry + MathAbs(entry - sl) * 3.0 : entry - MathAbs(entry - sl) * 3.0;

   // 🚨 【V6性能优化核心】：单次请求替代原有的可能循环调用
   long st_lvl = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   if(st_lvl > 0 && MathAbs(entry - sl) < st_lvl * point)
   {
      sl = (signal == 1) ? entry - st_lvl * point : entry + st_lvl * point;
      tp = (signal == 1) ? entry + st_lvl * point * 3.0 : entry - st_lvl * point * 3.0;
   }

   if(!CheckRiskRewardRatio(entry, sl, tp))
   {
      // Print("⚠️ 黑匣子: 盈亏比不足!");
      return;
   }
   
   double lots = CalculateSafeLotSize(MathAbs(entry - sl) / point);
   if(lots <= 0) return;

   for(int retry = 0; retry < 3; retry++)
   {
      if((signal == 1 && Trade.Buy(lots, _Symbol, entry, sl, tp)) || (signal == -1 && Trade.Sell(lots, _Symbol, entry, sl, tp)))
      {
         Print("✅ 狙击手开火！方向: ", (signal == 1 ? "BUY" : "SELL"), " 手数: ", lots, " 止损: ", sl);
         daily_loss_count = 0; 
         break;
      }
      else
      {
         int err = GetLastError();
         Print("❌ 开火失败，错误码: ", err);
         if(err == TRADE_RETCODE_REQUOTE || err == TRADE_RETCODE_PRICE_CHANGED || err == TRADE_RETCODE_TIMEOUT) 
         { 
            Sleep(100); 
            entry = (signal == 1) ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID); 
            continue; 
         }
         else if(err == TRADE_RETCODE_NO_MONEY) break;
         daily_loss_count++; break;
      }
   }
}
//+------------------------------------------------------------------+