//+------------------------------------------------------------------+
//|                                                  WallStreet_Sniper.mq5 |
//|                                     Generated by AI Quant Architect |
//|                                             Version 3.0 - 2026.04 |
//|                                                                  |
//| 风险提示：外汇、差价合约(CFDs)及加密货币等保证金交易具有高风险， |
//| 可能导致全部资金损失。本EA仅供学习和研究目的，不构成任何投资建议。 |
//| 过往回测表现不代表未来实盘结果。使用者应自行承担全部交易风险。   |
//+------------------------------------------------------------------+
#property copyright "AI Quant Architect"
#property version   "3.00"
#property description "WallStreet_Sniper V3.0 - 盈利导向型突破策略"
#property description "基于ATR动态止损、1:3风险回报比、复合动能突破策略"
#property description "风险提示：本EA包含严格风控机制，但仍可能产生亏损"

#include <Trade\Trade.mqh>

//+------------------------------------------------------------------+
//| 输入参数                                                         |
//+------------------------------------------------------------------+

input group "========== 核心风控模块 =========="
input int      Magic_Number         = 888888;
input double   Risk_Percentage      = 1.0;
input double   Min_Expectancy_Rate  = 0.1;
input int      Max_Continuous_Loss  = 5;
input double   Max_Daily_Drawdown   = 8.0;
input double   Max_Single_Loss_Rate = 3.0;

input group "========== 信号参数 =========="
input int      BreakoutPeriod       = 5;
input int      Trend_Filter_EMA     = 50;
input bool     Enable_Entity_Break  = false;
input int      ADXPeriod            = 14;
input double   ADXThreshold         = 10.0;
input int      GMT_Offset           = 0;
input int      TradingStartHour     = 0;
input int      TradingEndHour       = 24;

input group "========== 出场参数 =========="
input int      ATRPeriod            = 14;
input double   ATRMultiplier        = 1.2;
input bool     Enable_Break_Even    = true;
input int      Break_Even_Slippage  = 5;
input bool     Enable_Trailing_Stop = true;
input double   TrailingATRMultiplier = 1.0;

input group "========== 过滤参数 =========="
input int      MaxSpread            = 50;
input bool     Enable_Weekend_Close = true;
input bool     Enable_News_Filter   = true;
input int      News_Filter_Minutes  = 30;

input group "========== 推送通知 =========="
input string   MQID                 = "A736DD43";
input bool     Enable_Push          = true;
input bool     Enable_Daily_Report  = true;

//+------------------------------------------------------------------+
//| 全局变量                                                         |
//+------------------------------------------------------------------+
CTrade         Trade;
int            handle_ATR;
int            handle_EMA;
int            handle_ADX;
double         g_current_atr;
int            daily_loss_count;
double         daily_start_equity;
datetime       daily_reset_time;
double         cumulative_expectancy;
datetime       g_last_news_check_time;
bool           g_news_lock_flag;
bool           g_system_sleep;
datetime       g_last_report_time;
datetime       g_last_bar_time;
int            g_daily_trades;
double         g_daily_pnl;
double         g_total_win_amount;
double         g_total_loss_amount;
int            g_total_win;
int            g_total_loss;
int            g_last_expectancy_deals;

//+------------------------------------------------------------------+
//| 专家初始化函数                                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   Trade.SetExpertMagicNumber(Magic_Number);
   Trade.SetDeviationInPoints(10);

   handle_ATR = iATR(_Symbol, PERIOD_CURRENT, ATRPeriod);
   handle_EMA = iMA(_Symbol, PERIOD_CURRENT, Trend_Filter_EMA, 0, MODE_EMA, PRICE_CLOSE);
   handle_ADX = iADX(_Symbol, PERIOD_CURRENT, ADXPeriod);

   if(handle_ATR == INVALID_HANDLE || handle_EMA == INVALID_HANDLE || handle_ADX == INVALID_HANDLE)
   {
      Print("指标句柄创建失败，错误代码：", GetLastError());
      return INIT_FAILED;
   }

   if(Risk_Percentage > 2.0)
   {
      Print("风险百分比超限（", Risk_Percentage, "%），将使用2.0%上限");
   }

   g_current_atr = 0.0;
   daily_loss_count = 0;
   daily_start_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   daily_reset_time = 0;
   cumulative_expectancy = 0.0;
   g_last_news_check_time = 0;
   g_news_lock_flag = false;
   g_system_sleep = false;
   g_last_report_time = 0;
   g_last_bar_time = 0;
   g_daily_trades = 0;
   g_daily_pnl = 0.0;
   g_total_win_amount = 0.0;
   g_total_loss_amount = 0.0;
   g_total_win = 0;
   g_total_loss = 0;
   g_last_expectancy_deals = 0;

   Print("WallStreet_Sniper V3.0 初始化完成，魔术数字：", Magic_Number);
   Print("风险提示：本EA采用1:3风险回报比与动态仓位管理，请确保充分理解相关风险。");

   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| 专家反初始化函数                                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   if(handle_ATR != INVALID_HANDLE)
      IndicatorRelease(handle_ATR);
   if(handle_EMA != INVALID_HANDLE)
      IndicatorRelease(handle_EMA);
   if(handle_ADX != INVALID_HANDLE)
      IndicatorRelease(handle_ADX);

   Print("WallStreet_Sniper 已卸载，原因代码：", reason);
}

//+------------------------------------------------------------------+
//| 获取目标时区当前小时                                             |
//+------------------------------------------------------------------+
int GetTargetHour()
{
   MqlDateTime dt;
   TimeCurrent(dt);
   return ((dt.hour + GMT_Offset) % 24 + 24) % 24;
}

//+------------------------------------------------------------------+
//| 新K线检测                                                         |
//+------------------------------------------------------------------+
bool IsNewBar()
{
   datetime current_bar_time = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(current_bar_time == 0)
      return false;

   if(g_last_bar_time != current_bar_time)
   {
      g_last_bar_time = current_bar_time;
      return true;
   }

   return false;
}

//+------------------------------------------------------------------+
//| 错误码转文本描述                                                 |
//+------------------------------------------------------------------+
string GetLastErrorDescription(int error_code)
{
   switch(error_code)
   {
      case TRADE_RETCODE_REQUOTE:                 return "重新报价";
      case TRADE_RETCODE_INVALID_STOPS:           return "无效止损/止盈位";
      case TRADE_RETCODE_INVALID_PRICE:           return "无效价格";
      case TRADE_RETCODE_INVALID_VOLUME:          return "无效交易量";
      case TRADE_RETCODE_TIMEOUT:                 return "交易超时";
      case TRADE_RETCODE_PRICE_CHANGED:           return "价格已变动";
      case TRADE_RETCODE_PRICE_OFF:               return "报价丢失";
      case TRADE_RETCODE_TOO_MANY_REQUESTS:       return "请求过多";
      case TRADE_RETCODE_MARKET_CLOSED:           return "市场已关闭";
      case TRADE_RETCODE_TRADE_DISABLED:          return "交易被禁用";
      case TRADE_RETCODE_NO_MONEY:                return "资金不足";
      case TRADE_RETCODE_LOCKED:                  return "订单被锁定";
      case TRADE_RETCODE_REJECT:                  return "订单被拒绝";
      case TRADE_RETCODE_CANCEL:                  return "订单被取消";
      case TRADE_RETCODE_INVALID:                 return "无效请求";
      case TRADE_RETCODE_ERROR:                   return "执行错误";
      case TRADE_RETCODE_ORDER_CHANGED:           return "订单已变更";
      case TRADE_RETCODE_NO_CHANGES:              return "无变更";
      case TRADE_RETCODE_SERVER_DISABLES_AT:      return "服务器禁止自动执行";
      case TRADE_RETCODE_CLIENT_DISABLES_AT:      return "客户端禁止自动执行";
      case TRADE_RETCODE_INVALID_EXPIRATION:      return "无效过期时间";
      case TRADE_RETCODE_INVALID_FILL:            return "无效成交策略";
      default:                                    return "未知错误(" + (string)error_code + ")";
   }
}

//+------------------------------------------------------------------+
//| 推送通知工具函数                                                 |
//+------------------------------------------------------------------+
void PushNotification(string message)
{
   if(!Enable_Push)
      return;

   if(!SendNotification(message))
   {
      Print("推送通知失败，错误代码：", GetLastError());
   }
}

//+------------------------------------------------------------------+
//| 每日统计报告                                                     |
//+------------------------------------------------------------------+
void SendDailyReport()
{
   if(!Enable_Push || !Enable_Daily_Report)
      return;

   int target_hour = GetTargetHour();
   MqlDateTime dt;
   TimeCurrent(dt);

   if(dt.min == 0 && (target_hour == 12 || target_hour == 22))
   {
      if(TimeCurrent() - g_last_report_time >= 3600)
      {
         g_last_report_time = TimeCurrent();

         double balance = AccountInfoDouble(ACCOUNT_BALANCE);
         double equity = AccountInfoDouble(ACCOUNT_EQUITY);
         double profit = AccountInfoDouble(ACCOUNT_PROFIT);
         int positions = PositionsTotal();
         double drawdown = 0.0;
         if(daily_start_equity > 0.0)
            drawdown = (daily_start_equity - equity) / daily_start_equity * 100.0;

         string period = (target_hour == 12) ? "午间" : "晚间";
         string report = StringFormat("【WallStreet_Sniper %s报告(%d:00)】\n净值: %.2f\n余额: %.2f\n浮动盈亏: %.2f\n持仓: %d\n日内成交: %d笔\n日内盈亏: %.2f\n日内回撤: %.2f%%\n连亏次数: %d\n期望值: %.2f",
                                      period, target_hour, equity, balance, profit, positions,
                                      g_daily_trades, g_daily_pnl, drawdown,
                                      daily_loss_count, cumulative_expectancy);

         PushNotification(report);
      }
   }
}

//+------------------------------------------------------------------+
//| 仓位动态计算器                                                   |
//+------------------------------------------------------------------+
double CalculateSafeLotSize(double sl_points)
{
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double risk_pct = fmin(Risk_Percentage, 2.0);
   double risk_amount = equity * (risk_pct / 100.0);

   double tick_value = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tick_size = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);

   if(tick_value <= 0.0 || tick_size <= 0.0 || sl_points <= 0.0)
      return 0.0;

   double sl_value_per_lot = (sl_points * point / tick_size) * tick_value;
   if(sl_value_per_lot <= 0.0)
      return 0.0;

   double raw_lot = risk_amount / sl_value_per_lot;

   double lot_step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double min_lot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double max_lot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);

   if(lot_step > 0.0)
      raw_lot = MathFloor(raw_lot / lot_step) * lot_step;

   raw_lot = fmax(raw_lot, min_lot);
   raw_lot = fmin(raw_lot, max_lot);

   return raw_lot;
}

//+------------------------------------------------------------------+
//| 盈亏比强制校验卫士                                               |
//+------------------------------------------------------------------+
bool CheckRiskRewardRatio(double entry, double sl, double tp)
{
   double risk_distance = MathAbs(entry - sl);
   double reward_distance = MathAbs(tp - entry);

   if(risk_distance <= 0.0)
      return false;

   double ratio = reward_distance / risk_distance;

   if(ratio >= 3.0)
      return true;

   return false;
}

//+------------------------------------------------------------------+
//| 智能保本移动雷达 + ATR动态追踪止盈                               |
//+------------------------------------------------------------------+
void CheckBreakEvenAndTrailing()
{
   if(!Enable_Break_Even && !Enable_Trailing_Stop)
      return;

   if(g_current_atr <= 0.0)
      return;

   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double min_trail_step = g_current_atr * 0.3;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;

      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if(PositionGetInteger(POSITION_MAGIC) != Magic_Number)
         continue;

      double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
      double current_sl = PositionGetDouble(POSITION_SL);
      double current_tp = PositionGetDouble(POSITION_TP);
      long type = PositionGetInteger(POSITION_TYPE);
      double current_price = (type == POSITION_TYPE_BUY) ?
                              SymbolInfoDouble(_Symbol, SYMBOL_BID) :
                              SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double profit_distance = (type == POSITION_TYPE_BUY) ?
                                 current_price - open_price :
                                 open_price - current_price;

      if(profit_distance < g_current_atr * 0.5)
         continue;

      double be_sl = (type == POSITION_TYPE_BUY) ?
                        open_price + Break_Even_Slippage * point :
                        open_price - Break_Even_Slippage * point;

      if(Enable_Break_Even)
      {
         bool need_be = (type == POSITION_TYPE_BUY) ?
                           (current_sl < be_sl && current_price > be_sl) :
                           (current_sl > be_sl && current_price < be_sl);

         if(need_be)
         {
            if(Trade.PositionModify(ticket, be_sl, current_tp))
            {
               current_sl = be_sl;
            }
         }
      }

      if(Enable_Trailing_Stop)
      {
         bool is_be_protected = (type == POSITION_TYPE_BUY) ?
                                   (current_sl >= be_sl - point) :
                                   (current_sl <= be_sl + point);
         if(!is_be_protected)
            continue;

         double profit_after_be = (type == POSITION_TYPE_BUY) ?
                                    current_price - be_sl :
                                    be_sl - current_price;
         if(profit_after_be < g_current_atr * 0.3)
            continue;

         long stops_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
         double min_stops_distance = stops_level * point;

         double trailing_distance = g_current_atr * TrailingATRMultiplier;
         double new_trailing_sl = (type == POSITION_TYPE_BUY) ?
                                    current_price - trailing_distance :
                                    current_price + trailing_distance;

         if((type == POSITION_TYPE_BUY && new_trailing_sl < be_sl) ||
            (type == POSITION_TYPE_SELL && new_trailing_sl > be_sl))
            new_trailing_sl = be_sl;

         if(stops_level > 0 && MathAbs(current_price - new_trailing_sl) < min_stops_distance)
         {
            if(type == POSITION_TYPE_BUY)
               new_trailing_sl = current_price - min_stops_distance;
            else
               new_trailing_sl = current_price + min_stops_distance;

            if((type == POSITION_TYPE_BUY && new_trailing_sl < be_sl) ||
               (type == POSITION_TYPE_SELL && new_trailing_sl > be_sl))
               new_trailing_sl = be_sl;
         }

         double trail_distance = (type == POSITION_TYPE_BUY) ?
                                   new_trailing_sl - current_sl :
                                   current_sl - new_trailing_sl;

         if(trail_distance >= min_trail_step)
         {
            Trade.PositionModify(ticket, new_trailing_sl, current_tp);
         }
      }
   }
}

//+------------------------------------------------------------------+
//| 环境安全锁校验                                                   |
//+------------------------------------------------------------------+
bool IsEnvironmentSafe()
{
   int spread = (int)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(spread > MaxSpread)
   {
      if(MQLInfoInteger(MQL_TESTER))
      {
         // 回测放行
      }
      else
      {
         Print("环境恶劣，放弃交易：当前点差 ", spread, " 超过最大容忍值 ", MaxSpread);
         return false;
      }
   }

   double margin_required = 0.0;
   double ask_price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double min_lot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   if(!OrderCalcMargin(ORDER_TYPE_BUY, _Symbol, min_lot, ask_price, margin_required))
   {
      return false;
   }
   double free_margin = AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   if(free_margin < margin_required * 1.2)
   {
      Print("环境恶劣，放弃交易：可用保证金不足，可用：", free_margin, "，需求：", margin_required * 1.2);
      return false;
   }

   if(Enable_News_Filter && g_news_lock_flag)
   {
      Print("环境恶劣，放弃交易：高重要性新闻临近，禁止开仓");
      return false;
   }

   return true;
}

//+------------------------------------------------------------------+
//| 动能突破信号引擎                                                 |
//+------------------------------------------------------------------+
int CheckEntrySignal(double &current_atr)
{
   current_atr = 0.0;

   double atr_buffer[];
   if(CopyBuffer(handle_ATR, 0, 1, 1, atr_buffer) < 1)
      return 0;
   current_atr = atr_buffer[0];
   if(current_atr <= 0.0)
      return 0;

   double ema_buffer[];
   if(CopyBuffer(handle_EMA, 0, 1, 1, ema_buffer) < 1)
      return 0;
   double ema_value = ema_buffer[0];

   double adx_buffer[];
   if(CopyBuffer(handle_ADX, 0, 1, 1, adx_buffer) < 1)
      return 0;
   if(adx_buffer[0] < ADXThreshold)
      return 0;

   int target_hour = GetTargetHour();
   if(target_hour < TradingStartHour || target_hour >= TradingEndHour)
      return 0;

   double last_close = iClose(_Symbol, PERIOD_CURRENT, 1);
   double last_open = iOpen(_Symbol, PERIOD_CURRENT, 1);

   double highest_high = 0.0, lowest_low = DBL_MAX;
   for(int i = 2; i <= BreakoutPeriod + 1; i++)
   {
      double h = iHigh(_Symbol, PERIOD_CURRENT, i);
      double l = iLow(_Symbol, PERIOD_CURRENT, i);
      if(h > highest_high) highest_high = h;
      if(l < lowest_low) lowest_low = l;
   }
   if(highest_high == 0.0 || lowest_low == DBL_MAX)
      return 0;

   int signal = 0;

   if(last_close > highest_high && last_close > ema_value)
   {
      if(!Enable_Entity_Break || last_open > highest_high)
         signal = 1;
   }
   else if(last_close < lowest_low && last_close < ema_value)
   {
      if(!Enable_Entity_Break || last_open < lowest_low)
         signal = -1;
   }

   return signal;
}

//+------------------------------------------------------------------+
//| 强制平仓所有持仓                                                 |
//+------------------------------------------------------------------+
void CloseAllPositions()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if(PositionGetInteger(POSITION_MAGIC) != Magic_Number)
         continue;

      Trade.PositionClose(ticket);
   }
}

//+------------------------------------------------------------------+
//| 日内熔断检查                                                     |
//+------------------------------------------------------------------+
bool CheckDailyFuse()
{
   MqlDateTime dt;
   TimeCurrent(dt);
   datetime today_key = StructToTime(dt) - (dt.hour * 3600 + dt.min * 60 + dt.sec);

   if(daily_reset_time != today_key)
   {
      daily_reset_time = today_key;
      daily_start_equity = AccountInfoDouble(ACCOUNT_EQUITY);
      daily_loss_count = 0;
   }

   double current_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double drawdown_percent = 0.0;
   if(daily_start_equity > 0.0)
      drawdown_percent = (daily_start_equity - current_equity) / daily_start_equity * 100.0;

   if(drawdown_percent >= Max_Daily_Drawdown)
   {
      Print("日内回撤熔断触发：当前回撤 ", drawdown_percent, "%，阈值 ", Max_Daily_Drawdown, "%");
      PushNotification(StringFormat("【熔断】日内回撤 %.2f%% 触发，强制平仓", drawdown_percent));
      CloseAllPositions();
      return true;
   }

   if(daily_loss_count >= Max_Continuous_Loss)
   {
      Print("连续亏损熔断触发：亏损次数 ", daily_loss_count, "，阈值 ", Max_Continuous_Loss);
      PushNotification(StringFormat("【熔断】连续亏损 %d 次触发，强制平仓", daily_loss_count));
      CloseAllPositions();
      return true;
   }

   if(Enable_Weekend_Close && dt.day_of_week == 5 && dt.hour >= 20)
   {
      if(PositionsTotal() > 0)
      {
         Print("周末强平触发");
         PushNotification("【周末强平】周五收盘前强制平仓");
         CloseAllPositions();
      }
      return true;
   }

   if(dt.day_of_week == 6 || dt.day_of_week == 0)
   {
      if(PositionsTotal() > 0)
      {
         Print("周末强平触发");
         PushNotification("【周末强平】周末强制平仓");
         CloseAllPositions();
      }
      return true;
   }

   return false;
}

//+------------------------------------------------------------------+
//| 监控极端浮亏                                                     |
//+------------------------------------------------------------------+
void CheckExtremeLoss()
{
   double base_equity = (daily_start_equity > 0.0) ? daily_start_equity : AccountInfoDouble(ACCOUNT_EQUITY);

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol)
         continue;
      if(PositionGetInteger(POSITION_MAGIC) != Magic_Number)
         continue;

      double profit = PositionGetDouble(POSITION_PROFIT);
      if(profit < 0.0 && base_equity > 0.0)
      {
         double loss_rate = MathAbs(profit) / base_equity * 100.0;
         if(loss_rate >= Max_Single_Loss_Rate)
         {
            Print("极端浮亏监控：订单#", ticket, " 浮亏率 ", loss_rate, "%（基于日初净值），触发应急平仓");
            PushNotification(StringFormat("【极端浮亏】订单#%d 浮亏率 %.2f%%，应急平仓", ticket, loss_rate));
            if(Trade.PositionClose(ticket))
            {
               Print("极端浮亏平仓成功：订单#", ticket);
               PushNotification(StringFormat("【应急平仓成功】订单#%d 已平仓", ticket));
               daily_loss_count++;
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| 高重要性新闻过滤                                                 |
//+------------------------------------------------------------------+
void CheckHighImpactNews()
{
   if(!Enable_News_Filter)
      return;

   datetime current_time = TimeCurrent();
   if(current_time - g_last_news_check_time < 60)
      return;
   g_last_news_check_time = current_time;

   MqlDateTime dt;
   TimeCurrent(dt);

   bool in_news_zone = false;

   if(dt.day_of_week >= 1 && dt.day_of_week <= 5)
   {
      int hour = dt.hour;
      int min = dt.min;
      int total_min = hour * 60 + min;

      if((total_min >= 495 && total_min <= 525) ||
         (total_min >= 795 && total_min <= 825) ||
         (total_min >= 1330 && total_min <= 1360))
      {
         in_news_zone = true;
      }
   }

   g_news_lock_flag = in_news_zone;

   if(in_news_zone)
      Print("新闻封锁中：当前处于高影响力新闻时段，禁止开仓");
}

//+------------------------------------------------------------------+
//| 更新期望值统计                                                   |
//+------------------------------------------------------------------+
void UpdateExpectancy()
{
   int total_deals = g_total_win + g_total_loss;
   if(total_deals <= g_last_expectancy_deals)
      return;

   g_last_expectancy_deals = total_deals;

   if(total_deals < 10)
      return;

   if(total_deals > 0)
   {
      double win_rate = (double)g_total_win / total_deals;
      double avg_win = 0.0, avg_loss = 0.0;
      if(g_total_win > 0)
         avg_win = g_total_win_amount / g_total_win;
      if(g_total_loss > 0)
         avg_loss = MathAbs(g_total_loss_amount) / g_total_loss;

      if(avg_loss > 0)
         cumulative_expectancy = (win_rate * avg_win) - ((1.0 - win_rate) * avg_loss);
      else
         cumulative_expectancy = (g_total_win_amount + g_total_loss_amount) / total_deals;

      Print("期望值校验：最近", total_deals, "笔交易，期望值 = ", cumulative_expectancy);

      if(cumulative_expectancy < Min_Expectancy_Rate)
      {
         g_system_sleep = true;
         Print("系统期望值 ", cumulative_expectancy, " 低于最低阈值 ", Min_Expectancy_Rate, "，系统进入休眠状态");
      }
      else
      {
         g_system_sleep = false;
      }
   }
}

//+------------------------------------------------------------------+
//| 交易事件监听                                                     |
//+------------------------------------------------------------------+
void OnTradeTransaction(const MqlTradeTransaction &trans,
                        const MqlTradeRequest &request,
                        const MqlTradeResult &result)
{
   if(trans.type != TRADE_TRANSACTION_DEAL_ADD)
      return;

   ulong deal_ticket = trans.deal;
   if(deal_ticket == 0)
      return;

   long deal_magic = HistoryDealGetInteger(deal_ticket, DEAL_MAGIC);
   if(deal_magic != Magic_Number)
      return;

   string symbol = HistoryDealGetString(deal_ticket, DEAL_SYMBOL);
   if(symbol != _Symbol)
      return;

   long deal_entry = HistoryDealGetInteger(deal_ticket, DEAL_ENTRY);
   if(deal_entry != DEAL_ENTRY_OUT)
      return;

   long deal_type = HistoryDealGetInteger(deal_ticket, DEAL_TYPE);
   double profit = HistoryDealGetDouble(deal_ticket, DEAL_PROFIT);
   double volume = HistoryDealGetDouble(deal_ticket, DEAL_VOLUME);
   double price = HistoryDealGetDouble(deal_ticket, DEAL_PRICE);

   g_daily_trades++;
   g_daily_pnl += profit;

   if(profit > 0)
   {
      g_total_win_amount += profit;
      g_total_win++;
   }
   else if(profit < 0)
   {
      g_total_loss_amount += profit;
      g_total_loss++;
   }

   UpdateExpectancy();

   if(Enable_Push && (deal_type == DEAL_TYPE_SELL || deal_type == DEAL_TYPE_BUY))
   {
      string dir = (deal_type == DEAL_TYPE_SELL) ? "多单平仓" : "空单平仓";
      string pnl_str = (profit >= 0) ? StringFormat("+%.2f", profit) : StringFormat("%.2f", profit);
      PushNotification(StringFormat("【平仓结算】%s %.2f手 价格%.5f 盈亏%s", dir, volume, price, pnl_str));
   }
}

//+------------------------------------------------------------------+
//| 专家Tick函数（系统心脏）                                         |
//+------------------------------------------------------------------+
void OnTick()
{
   SendDailyReport();

   if(CheckDailyFuse())
      return;

   CheckHighImpactNews();

   double atr_buffer_new[];
   if(CopyBuffer(handle_ATR, 0, 0, 1, atr_buffer_new) >= 1)
      g_current_atr = atr_buffer_new[0];

   CheckBreakEvenAndTrailing();
   CheckExtremeLoss();

   if(g_system_sleep)
      return;

   if(!IsEnvironmentSafe())
      return;

   if(!IsNewBar())
      return;

   if(BarsCalculated(handle_ATR) < BreakoutPeriod ||
      BarsCalculated(handle_EMA) < BreakoutPeriod ||
      BarsCalculated(handle_ADX) < BreakoutPeriod)
      return;

   double current_atr = 0.0;
   int signal = CheckEntrySignal(current_atr);
   if(current_atr > 0.0)
      g_current_atr = current_atr;

   if(signal == 0)
      return;

   double entry_price = 0.0;
   double sl_price = 0.0;
   double tp_price = 0.0;
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);

   int spread_points = (int)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);

   if(signal == 1)
   {
      entry_price = ask;
      sl_price = entry_price - current_atr * ATRMultiplier - spread_points * point;
      tp_price = entry_price + MathAbs(entry_price - sl_price) * 3.0;
   }
   else if(signal == -1)
   {
      entry_price = bid;
      sl_price = entry_price + current_atr * ATRMultiplier + spread_points * point;
      tp_price = entry_price - MathAbs(entry_price - sl_price) * 3.0;
   }

   long stops_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   if(stops_level > 0)
   {
      double stops_distance = stops_level * point;
      if(MathAbs(entry_price - sl_price) < stops_distance)
      {
         if(signal == 1)
            sl_price = entry_price - stops_distance;
         else
            sl_price = entry_price + stops_distance;
      }
      if(MathAbs(tp_price - entry_price) < stops_distance)
      {
         if(signal == 1)
            tp_price = entry_price + stops_distance;
         else
            tp_price = entry_price - stops_distance;
      }
   }

   if(!CheckRiskRewardRatio(entry_price, sl_price, tp_price))
      return;

   double sl_points = MathAbs(entry_price - sl_price) / point;
   double lot_size = CalculateSafeLotSize(sl_points);

   if(lot_size <= 0.0)
      return;

   bool order_sent = false;
   for(int retry = 0; retry < 3; retry++)
   {
      if(signal == 1)
      {
         order_sent = Trade.Buy(lot_size, _Symbol, entry_price, sl_price, tp_price);
      }
      else if(signal == -1)
      {
         order_sent = Trade.Sell(lot_size, _Symbol, entry_price, sl_price, tp_price);
      }

      if(order_sent)
      {
         string direction = (signal == 1 ? "BUY" : "SELL");
         Print("开仓成功：方向=", direction,
               ", 手数=", lot_size,
               ", 入场价=", entry_price,
               ", 止损=", sl_price,
               ", 止盈=", tp_price,
               ", ATR=", current_atr);
         PushNotification(StringFormat("【开仓】%s %.2f手 入场%.5f 止损%.5f 止盈%.5f",
                          direction, lot_size, entry_price, sl_price, tp_price));
         daily_loss_count = 0;
         break;
      }
      else
      {
         int error = GetLastError();

         switch(error)
         {
            case TRADE_RETCODE_REQUOTE:
               Sleep(100);
               bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
               ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
               if(signal == 1)
                  entry_price = ask;
               else
                  entry_price = bid;
               continue;

            case TRADE_RETCODE_INVALID_STOPS:
               stops_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
               if(stops_level > 0)
               {
                  double stops_distance = stops_level * point;
                  if(signal == 1)
                  {
                     sl_price = entry_price - stops_distance;
                     tp_price = entry_price + stops_distance * 3.0;
                  }
                  else
                  {
                     sl_price = entry_price + stops_distance;
                     tp_price = entry_price - stops_distance * 3.0;
                  }
               }
               continue;

            case TRADE_RETCODE_TIMEOUT:
               Sleep(3000);
               continue;

            case TRADE_RETCODE_PRICE_CHANGED:
               bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
               ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
               if(signal == 1)
               {
                  entry_price = ask;
                  sl_price = entry_price - current_atr * ATRMultiplier - spread_points * point;
                  tp_price = entry_price + MathAbs(entry_price - sl_price) * 3.0;
               }
               else
               {
                  entry_price = bid;
                  sl_price = entry_price + current_atr * ATRMultiplier + spread_points * point;
                  tp_price = entry_price - MathAbs(entry_price - sl_price) * 3.0;
               }
               continue;

            case TRADE_RETCODE_NO_MONEY:
               Print("资金不足，放弃开仓");
               break;

            default:
               daily_loss_count++;
               break;
         }
         break;
      }
   }

}