#!/usr/bin/env python3
"""Generate the TASK-066 runtime report quality audit report."""

from datetime import datetime, timezone
import json
from pathlib import Path
import sys


CURRENT_LATEST_COMMIT = "fc50e8d TASK-DOC-064 update state after TASK-065"
CURRENT_FUNCTIONAL_TASK = "28d1c87 TASK-065 reject prohibited runtime report claims"
CURRENT_STABLE_TAG = "v0.1.8-engineering-toolchain-stable"
PREVIOUS_STABLE_TAG_REFERENCE = "v0.1.7-core-signal-log-throttle"
REPORT_RELATIVE_PATH = (
    "backtest/reports/generated/TASK-066_runtime_report_quality_audit.md"
)

COMPLETED_SCOPE = [
    "Missing Field Notes",
    "Missing fields count consistency validation",
    "Missing field list consistency validation",
    "Field Coverage Summary",
    "Field Coverage Summary validation",
    "Signal Observation Summary",
    "Signal Observation Summary validation",
    "Risk Rejection Summary",
    "Risk Rejection Summary validation",
    "Log Throttle Summary",
    "Log Throttle Summary validation",
    "Runtime report required section order validation",
    "Unknown runtime report section rejection",
    "Prohibited runtime report claims rejection",
]

CURRENT_GENERATED_REPORTS = [
    "backtest/reports/generated/TASK-012_generated_runtime_summary_sample.md",
    "backtest/reports/generated/TASK-012_generated_TASK-010_v0.1.7_core_signal_log_throttle.md",
]

REQUIRED_RUNTIME_REPORT_SECTIONS = [
    "Report Metadata",
    "Runtime Summary Counters",
    "Runtime Summary Signal Stats",
    "Runtime Summary Risk Reject Stats",
    "Runtime Summary Risk Log Stats",
    "Runtime Summary Core / New Bar Log Stats",
    "Runtime Summary Signal Log Stats",
    "Final Balance",
    "Field Coverage Summary",
    "Signal Observation Summary",
    "Risk Rejection Summary",
    "Log Throttle Summary",
    "Missing Field Notes",
    "Safety Notes",
]

EXPECTED_COMMANDS = [
    "py tools/validate_backtest_runtime_report.py --report backtest/reports/generated/TASK-012_generated_runtime_summary_sample.md",
    "py tools/validate_backtest_runtime_report.py --report backtest/reports/generated/TASK-012_generated_TASK-010_v0.1.7_core_signal_log_throttle.md",
    "py tools/test_validate_backtest_runtime_report.py",
    "py tools/run_engineering_toolchain_checks.py",
    "py tools/validate_project_state_docs.py",
    "py tools/test_validate_project_state_docs.py",
    "py tools/validate_mq5_safety_guardrails.py",
    "py tools/test_validate_mq5_safety_guardrails.py",
    "py tools/validate_backtest_set_safety.py",
    "py tools/test_validate_backtest_set_safety.py",
    "py tools/validate_python_tool_safety.py",
    "py tools/test_validate_python_tool_safety.py",
]

SAFETY_STATUS = [
    "Current system is still not allowed to perform real trading.",
    "SignalEngine must not place orders.",
    "RiskManager must not be bypassed.",
    "ExecutionManager must not execute real orders in the current stage.",
    "InpEnableTrading default remains false.",
    "CTrade / OrderSend / PositionOpen / Buy / Sell / OrderModify remain forbidden in current stage.",
    "Martingale, grid, and averaging-down remain forbidden.",
    "EMA signals remain observation-only and are not a production trading strategy.",
    "Runtime reports must not contain trading recommendations.",
    "Runtime reports must not contain profit conclusions.",
    "Runtime reports must not claim live trading readiness.",
]

NOT_INCLUDED = [
    "No ATR implementation.",
    "No position sizing.",
    "No stop loss / take profit implementation.",
    "No AI trading logic.",
    "No multi-symbol trading.",
    "No multi-account trading.",
    "No live execution.",
    "No tag creation.",
    "No strategy optimization.",
]


def bullet_lines(items):
    return [f"- {item}" for item in items]


def numbered_lines(items):
    return [f"{index}. {item}" for index, item in enumerate(items, start=1)]


def build_report():
    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    required_sections_json = json.dumps(
        [
            {"index": index, "section": section}
            for index, section in enumerate(REQUIRED_RUNTIME_REPORT_SECTIONS, start=1)
        ],
        ensure_ascii=True,
    )

    lines = [
        "# Runtime Report Quality Audit",
        "",
        "## Report Metadata",
        "",
        "- Report Type: Runtime Report Quality Audit",
        "- Generated By: tools/generate_runtime_report_quality_audit.py",
        f"- Generated At UTC: {generated_at}",
        f"- Current Latest Commit: {CURRENT_LATEST_COMMIT}",
        f"- Current Latest Functional Task: {CURRENT_FUNCTIONAL_TASK}",
        f"- Current Stable Tag: {CURRENT_STABLE_TAG}",
        f"- Previous Stable Tag Reference: {PREVIOUS_STABLE_TAG_REFERENCE}",
        "- Tag Created In This Task: No",
        "",
        "## Scope",
        "",
        "- This audit summarizes the v0.1.9 runtime report quality stage.",
        "- This audit does not enable real trading.",
        "- This audit does not modify MQ5.",
        "- This audit does not modify backtest/sets.",
        "- This audit does not create a tag.",
        "",
        "## Completed Runtime Report Quality Scope",
        "",
        *bullet_lines(COMPLETED_SCOPE),
        "",
        "## Current Generated Runtime Reports",
        "",
        *bullet_lines(CURRENT_GENERATED_REPORTS),
        "",
        "## Required Runtime Report Sections",
        "",
        *numbered_lines(REQUIRED_RUNTIME_REPORT_SECTIONS),
        "",
        "Machine-readable required section snapshot:",
        "",
        "```json",
        required_sections_json,
        "```",
        "",
        "## Expected Verification Commands",
        "",
        "```text",
        *EXPECTED_COMMANDS,
        "```",
        "",
        "## Safety Status",
        "",
        *bullet_lines(SAFETY_STATUS),
        "",
        "## Not Included",
        "",
        *bullet_lines(NOT_INCLUDED),
        "",
        "## Audit Conclusion",
        "",
        "- Runtime report quality stage is ready for final manual verification.",
        "- Tag creation is not part of TASK-066.",
        "- A future tag decision must be made explicitly by ChatGPT after manual verification.",
        "",
    ]
    return "\n".join(lines)


def main():
    project_root = Path(__file__).resolve().parents[1]
    output_path = project_root / REPORT_RELATIVE_PATH
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_report(), encoding="utf-8")
    print("Runtime report quality audit generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
