#!/usr/bin/env python3
"""Validate generated backtest runtime summary draft reports."""

import argparse
from pathlib import Path
import re
import sys


REQUIRED_SUBSTRINGS = [
    "Report Type: Draft / 草稿",
    "Generated By: tools/parse_backtest_runtime_summary.py",
    "## Runtime Summary Counters",
    "## Runtime Summary Signal Stats",
    "## Runtime Summary Risk Reject Stats",
    "## Runtime Summary Risk Log Stats",
    "## Runtime Summary Core / New Bar Log Stats",
    "## Runtime Summary Signal Log Stats",
    "## Final Balance",
    "## Field Coverage Summary",
    "Total runtime fields:",
    "Found runtime fields:",
    "Missing runtime fields:",
    "Missing field ratio:",
    "## Signal Observation Summary",
    "signalsEvaluated:",
    "buySignals:",
    "sellSignals:",
    "noneSignals:",
    "signalDirectionChanges:",
    "Signal observation fields found:",
    "Signal observation fields missing:",
    "Missing signal observation fields:",
    "Signals are observation-only and are not trading instructions.",
    "Signal observation values are parsed from source text only.",
    "Not found signal fields are not inferred.",
    "This section does not enable real trading.",
    "## Risk Rejection Summary",
    "riskRejected:",
    "riskApproved:",
    "totalRiskRejects:",
    "riskRejectSignalNone:",
    "riskRejectTradingDisabled:",
    "riskRejectInvalidPrice:",
    "riskRejectSpreadTooHigh:",
    "riskRejectTimeBlocked:",
    "riskRejectMaxPositions:",
    "riskRejectObservationMode:",
    "Risk rejection fields found:",
    "Risk rejection fields missing:",
    "Missing risk rejection fields:",
    "Risk rejection values are parsed from source text only.",
    "Not found risk rejection fields are not inferred.",
    "Risk rejection summary does not enable real trading.",
    "RiskManager must not be bypassed.",
    "## Log Throttle Summary",
    "printedRiskRejectLogs:",
    "suppressedRiskRejectLogs:",
    "totalNewBarLogEvents:",
    "printedNewBarLogs:",
    "suppressedNewBarLogs:",
    "totalSignalLogEvents:",
    "printedSignalLogs:",
    "suppressedSignalLogs:",
    "Risk reject log print ratio:",
    "New bar log print ratio:",
    "Signal log print ratio:",
    "Log throttle fields found:",
    "Log throttle fields missing:",
    "Missing log throttle fields:",
    "Log throttle values are parsed from source text only.",
    "Not found log throttle fields are not inferred.",
    "Log throttle summary does not enable real trading.",
    "Log throttle ratios are reporting metrics, not trading signals.",
    "## Missing Field Notes",
    "Missing fields count:",
    "Missing fields are reported as Not found.",
    "Not found means the field was not present in the parsed source text.",
    "Not found values are not inferred.",
    "Not found does not mean zero.",
    "Not found does not mean the backtest failed.",
    "Parser output is based on parsed text only.",
    "## Safety Notes",
    "This is a draft generated from parsed text only.",
    "The current system is not allowed to perform real trading.",
    "EMA signals are observation-only and are not a production trading strategy.",
    "RiskManager must not be bypassed.",
    "ExecutionManager must not execute real orders in the current stage.",
    "Missing fields are reported as Not found and are not inferred.",
]

REQUIRED_REPORT_TITLE = "# Backtest Runtime Summary Draft"

REQUIRED_SECTION_HEADINGS = [
    "## Report Metadata",
    "## Runtime Summary Counters",
    "## Runtime Summary Signal Stats",
    "## Runtime Summary Risk Reject Stats",
    "## Runtime Summary Risk Log Stats",
    "## Runtime Summary Core / New Bar Log Stats",
    "## Runtime Summary Signal Log Stats",
    "## Final Balance",
    "## Field Coverage Summary",
    "## Signal Observation Summary",
    "## Risk Rejection Summary",
    "## Log Throttle Summary",
    "## Missing Field Notes",
    "## Safety Notes",
]

PROHIBITED_CONTENT_PHRASES = [
    "buy recommendation",
    "sell recommendation",
    "trading recommendation",
    "recommended trade",
    "should buy",
    "should sell",
    "enter long",
    "enter short",
    "买入建议",
    "卖出建议",
    "交易建议",
    "做多建议",
    "做空建议",
    "profitable strategy",
    "profit guaranteed",
    "guaranteed profit",
    "expected profit",
    "profit recommendation",
    "盈利策略",
    "保证盈利",
    "稳定盈利",
    "收益建议",
    "盈利结论",
    "live trading ready",
    "ready for live trading",
    "real trading enabled",
    "production trading ready",
    "can be used for real trading",
    "suitable for live trading",
    "实盘可用",
    "可以实盘",
    "允许实盘",
    "已开启真实交易",
    "可用于真实交易",
    "RiskManager can be bypassed",
    "bypass RiskManager",
    "ExecutionManager can execute real orders",
    "SignalEngine can place orders",
    "可以绕过 RiskManager",
    "绕过风控",
    "可以真实下单",
    "SignalEngine 可以下单",
    "strategy optimization recommendation",
    "optimize for profit",
    "parameter optimization recommendation",
    "策略优化建议",
    "参数优化建议",
    "盈利优化建议",
]


def extract_section(text, heading):
    pattern = re.compile(
        r"^" + re.escape(heading) + r"\s*$([\s\S]*?)(?=^## |\Z)",
        re.MULTILINE,
    )
    match = pattern.search(text)
    if match is None:
        return ""
    return match.group(1)


def find_section_order_issues(text):
    issues = []

    title_matches = re.findall(
        r"^" + re.escape(REQUIRED_REPORT_TITLE) + r"\s*$",
        text,
        re.MULTILINE,
    )
    if len(title_matches) != 1:
        issues.append(REQUIRED_REPORT_TITLE)

    section_headings = re.findall(r"^##\s+[^\r\n]+$", text, re.MULTILINE)
    required_set = set(REQUIRED_SECTION_HEADINGS)

    for heading in REQUIRED_SECTION_HEADINGS:
        count = section_headings.count(heading)
        if count == 0:
            issues.append(heading)
        elif count > 1:
            issues.append(f"Duplicate required section: {heading}")

    for heading in section_headings:
        if heading not in required_set:
            issues.append(f"unknown report section: {heading}")

    if section_headings != REQUIRED_SECTION_HEADINGS:
        issues.append("Section order mismatch")

    return issues


def find_prohibited_content_issues(text):
    issues = []
    normalized_text = text.lower()

    for phrase in PROHIBITED_CONTENT_PHRASES:
        if phrase.lower() in normalized_text:
            issues.append(f"prohibited runtime report content: {phrase}")

    return issues


def find_not_found_fields(text):
    not_found_fields = []
    for field in RUNTIME_SUMMARY_FIELDS:
        pattern = re.compile(
            r"^-\s+" + re.escape(field) + r"\s*:\s*Not found\s*$",
            re.MULTILINE,
        )
        if pattern.search(text):
            not_found_fields.append(field)
    return not_found_fields


def find_not_found_fields_for_coverage(text):
    not_found_fields = []
    for field in REQUIRED_FIELDS:
        pattern = re.compile(
            r"^-\s+" + re.escape(field) + r"\s*:\s*Not found\s*$",
            re.MULTILINE,
        )
        if pattern.search(text):
            not_found_fields.append(field)
    return not_found_fields


def parse_bullet_value(section_text, field):
    match = re.search(
        r"^\s*-\s+" + re.escape(field) + r"\s*:\s*([^\r\n]+)\s*$",
        section_text,
        re.MULTILINE,
    )
    if match is None:
        return None
    return match.group(1).strip()


def parse_report_field_value(text, field):
    match = re.search(
        r"^-\s+" + re.escape(field) + r"\s*:\s*([^\r\n]+)\s*$",
        text,
        re.MULTILINE,
    )
    if match is None:
        return None
    return match.group(1).strip()


def parse_missing_fields_count(notes):
    match = re.search(r"Missing fields count:\s*([^\r\n]+)", notes)
    if match is None:
        return None, "Missing fields count"

    raw_count = match.group(1).strip()
    if not re.fullmatch(r"\d+", raw_count):
        return None, "Missing fields count is not an integer"

    return int(raw_count), ""


def find_listed_missing_fields(notes):
    listed_fields = []
    in_missing_fields = False

    for line in notes.splitlines():
        stripped = line.strip()
        if stripped == "- Missing fields:":
            in_missing_fields = True
            continue

        if not in_missing_fields:
            continue

        if not stripped:
            continue

        if not line.startswith("  - "):
            in_missing_fields = False
            continue

        field = line.strip()[2:].strip()
        if field:
            listed_fields.append(field)

    return listed_fields


def find_listed_signal_observation_missing_fields(section_text):
    none_match = re.search(
        r"^\s*-\s+Missing signal observation fields:\s*none\s*$",
        section_text,
        re.MULTILINE,
    )
    if none_match is not None:
        return "none", []

    listed_fields = []
    in_missing_fields = False

    for line in section_text.splitlines():
        stripped = line.strip()
        if stripped == "- Missing signal observation fields:":
            in_missing_fields = True
            continue

        if not in_missing_fields:
            continue

        if not stripped:
            continue

        if not line.startswith("  - "):
            in_missing_fields = False
            continue

        field = line.strip()[2:].strip()
        if field:
            listed_fields.append(field)

    return "list", listed_fields


def find_listed_risk_rejection_missing_fields(section_text):
    none_match = re.search(
        r"^\s*-\s+Missing risk rejection fields:\s*none\s*$",
        section_text,
        re.MULTILINE,
    )
    if none_match is not None:
        return "none", []

    listed_fields = []
    in_missing_fields = False

    for line in section_text.splitlines():
        stripped = line.strip()
        if stripped == "- Missing risk rejection fields:":
            in_missing_fields = True
            continue

        if not in_missing_fields:
            continue

        if not stripped:
            continue

        if not line.startswith("  - "):
            in_missing_fields = False
            continue

        field = line.strip()[2:].strip()
        if field:
            listed_fields.append(field)

    return "list", listed_fields


def find_listed_log_throttle_missing_fields(section_text):
    none_match = re.search(
        r"^\s*-\s+Missing log throttle fields:\s*none\s*$",
        section_text,
        re.MULTILINE,
    )
    if none_match is not None:
        return "none", []

    listed_fields = []
    in_missing_fields = False

    for line in section_text.splitlines():
        stripped = line.strip()
        if stripped == "- Missing log throttle fields:":
            in_missing_fields = True
            continue

        if not in_missing_fields:
            continue

        if not stripped:
            continue

        if not line.startswith("  - "):
            in_missing_fields = False
            continue

        field = line.strip()[2:].strip()
        if field:
            listed_fields.append(field)

    return "list", listed_fields


def parse_labeled_int(section_text, label):
    match = re.search(
        r"^\s*-\s+" + re.escape(label) + r":\s*([^\r\n]+)\s*$",
        section_text,
        re.MULTILINE,
    )
    if match is None:
        return None, f"{label}"

    raw_value = match.group(1).strip()
    if not re.fullmatch(r"\d+", raw_value):
        return None, f"{label} is not an integer"

    return int(raw_value), ""


def parse_missing_field_ratio(section_text):
    match = re.search(
        r"^\s*-\s+Missing field ratio:\s*([^\r\n]+)\s*$",
        section_text,
        re.MULTILINE,
    )
    if match is None:
        return None, "Missing field ratio"

    raw_ratio = match.group(1).strip()
    if not re.fullmatch(r"\d+(?:\.\d+)?%", raw_ratio):
        return None, "Missing field ratio is not a percentage"

    return float(raw_ratio[:-1]), ""


def parse_labeled_ratio(section_text, label):
    match = re.search(
        r"^\s*-\s+" + re.escape(label) + r":\s*([^\r\n]+)\s*$",
        section_text,
        re.MULTILINE,
    )
    if match is None:
        return None, f"{label}"

    raw_ratio = match.group(1).strip()
    if raw_ratio == "Not found":
        return raw_ratio, ""
    if not re.fullmatch(r"\d+(?:\.\d+)?%", raw_ratio):
        return None, f"{label} is not a percentage"

    return raw_ratio, ""


def parse_non_negative_int(value):
    if value is None or value == "Not found":
        return None
    if not re.fullmatch(r"\d+", value):
        return None
    return int(value)


def expected_log_ratio(numerator, denominator):
    if numerator is None or denominator is None:
        return "Not found"
    if denominator == 0:
        return "0.00%"
    return f"{(numerator / denominator * 100):.2f}%"


def parse_section_distribution(section_text, section_title):
    pattern = re.compile(
        r"^\s*-\s+"
        + re.escape(section_title)
        + r":\s*found\s+([^\s]+)\s*/\s*missing\s+([^\s]+)\s*$",
        re.MULTILINE,
    )
    match = pattern.search(section_text)
    if match is None:
        return None, None, f"Field coverage section missing: {section_title}"

    found_raw = match.group(1).strip()
    missing_raw = match.group(2).strip()
    if not re.fullmatch(r"\d+", found_raw) or not re.fullmatch(r"\d+", missing_raw):
        return None, None, f"Field coverage section values invalid: {section_title}"

    return int(found_raw), int(missing_raw), ""


def count_section_found_missing(text, fields):
    missing = 0
    for field in fields:
        pattern = re.compile(
            r"^-\s+" + re.escape(field) + r"\s*:\s*Not found\s*$",
            re.MULTILINE,
        )
        if pattern.search(text):
            missing += 1
    return len(fields) - missing, missing


def find_field_coverage_issues(text):
    issues = []
    coverage = extract_section(text, "## Field Coverage Summary")
    if not coverage:
        return ["Field Coverage Summary section"]

    total, total_issue = parse_labeled_int(coverage, "Total runtime fields")
    found, found_issue = parse_labeled_int(coverage, "Found runtime fields")
    missing, missing_issue = parse_labeled_int(coverage, "Missing runtime fields")
    ratio, ratio_issue = parse_missing_field_ratio(coverage)

    for issue in (total_issue, found_issue, missing_issue, ratio_issue):
        if issue:
            issues.append(issue)

    expected_total = sum(len(fields) for _, fields in SECTION_FIELDS)
    actual_missing = len(find_not_found_fields_for_coverage(text))
    actual_found = expected_total - actual_missing

    if total is not None:
        if total == 0:
            issues.append("Total runtime fields is zero")
        elif total != expected_total:
            issues.append(
                f"Total runtime fields mismatch: expected {expected_total}, found {total}"
            )

    if None not in (total, found, missing):
        if total != found + missing:
            issues.append("Field coverage total mismatch")

    if found is not None and found != actual_found:
        issues.append(
            f"Field coverage found mismatch: expected {actual_found}, found {found}"
        )

    if missing is not None and missing != actual_missing:
        issues.append(
            f"Field coverage missing mismatch: expected {actual_missing}, found {missing}"
        )

    if total is not None and total > 0 and ratio is not None:
        expected_ratio = round((actual_missing / total) * 100, 2)
        if abs(ratio - expected_ratio) > 0.005:
            issues.append(
                f"Missing field ratio mismatch: expected {expected_ratio:.2f}%, found {ratio:.2f}%"
            )

    section_found_total = 0
    section_missing_total = 0
    for section_title, fields in SECTION_FIELDS:
        section_found, section_missing, section_issue = parse_section_distribution(
            coverage, section_title
        )
        if section_issue:
            issues.append(section_issue)
            continue

        expected_found, expected_missing = count_section_found_missing(text, fields)
        section_found_total += section_found
        section_missing_total += section_missing

        if section_found != expected_found or section_missing != expected_missing:
            issues.append(f"Field coverage section mismatch: {section_title}")

    if found is not None and missing is not None:
        if section_found_total != found or section_missing_total != missing:
            issues.append("Field coverage section totals mismatch")

    return issues


def find_signal_observation_issues(text):
    issues = []
    section = extract_section(text, "## Signal Observation Summary")
    if not section:
        return ["Signal Observation Summary section"]

    for required in (
        "Signals are observation-only and are not trading instructions.",
        "Signal observation values are parsed from source text only.",
        "Not found signal fields are not inferred.",
        "This section does not enable real trading.",
    ):
        if required not in section:
            issues.append(required)

    actual_values = {}
    for field in SIGNAL_OBSERVATION_FIELDS:
        report_value = parse_report_field_value(text, field)
        summary_value = parse_bullet_value(section, field)
        if summary_value is None:
            issues.append(f"Signal Observation Summary missing field: {field}")
            continue
        if report_value is None:
            issues.append(f"Runtime summary missing signal field: {field}")
            continue
        actual_values[field] = report_value
        if summary_value != report_value:
            issues.append(f"Signal Observation Summary value mismatch: {field}")

    found_count, found_issue = parse_labeled_int(
        section, "Signal observation fields found"
    )
    missing_count, missing_issue = parse_labeled_int(
        section, "Signal observation fields missing"
    )
    if found_issue:
        issues.append(found_issue)
    if missing_issue:
        issues.append(missing_issue)

    actual_missing_fields = [
        field
        for field in SIGNAL_OBSERVATION_FIELDS
        if actual_values.get(field) == "Not found"
    ]
    actual_found_count = len(SIGNAL_OBSERVATION_FIELDS) - len(actual_missing_fields)

    if found_count is not None and found_count != actual_found_count:
        issues.append(
            f"Signal observation found mismatch: expected {actual_found_count}, found {found_count}"
        )
    if missing_count is not None and missing_count != len(actual_missing_fields):
        issues.append(
            "Signal observation missing mismatch: "
            f"expected {len(actual_missing_fields)}, found {missing_count}"
        )

    missing_mode, listed_fields = find_listed_signal_observation_missing_fields(section)
    if not actual_missing_fields:
        if missing_mode != "none":
            issues.append("Signal observation missing fields should be none")
        if listed_fields:
            issues.append("Signal observation unexpected missing field list")
    else:
        if missing_mode == "none" or not listed_fields:
            issues.append("Signal observation missing field list")

        actual_field_set = set(actual_missing_fields)
        listed_field_set = set(listed_fields)

        for field in listed_fields:
            if field not in SIGNAL_OBSERVATION_FIELDS:
                issues.append(f"Unknown Signal Observation missing field: {field}")

        for field in actual_missing_fields:
            if field not in listed_field_set:
                issues.append(f"Signal Observation missing field: {field}")

        for field in listed_fields:
            if field in SIGNAL_OBSERVATION_FIELDS and field not in actual_field_set:
                issues.append(f"Signal Observation unexpected missing field: {field}")

    return issues


def find_risk_rejection_issues(text):
    issues = []
    section = extract_section(text, "## Risk Rejection Summary")
    if not section:
        return ["Risk Rejection Summary section"]

    for required in (
        "Risk rejection values are parsed from source text only.",
        "Not found risk rejection fields are not inferred.",
        "Risk rejection summary does not enable real trading.",
        "RiskManager must not be bypassed.",
    ):
        if required not in section:
            issues.append(required)

    actual_values = {}
    for field in RISK_REJECTION_FIELDS:
        report_value = parse_report_field_value(text, field)
        summary_value = parse_bullet_value(section, field)
        if summary_value is None:
            issues.append(f"Risk Rejection Summary missing field: {field}")
            continue
        if report_value is None:
            issues.append(f"Runtime summary missing risk rejection field: {field}")
            continue
        actual_values[field] = report_value
        if summary_value != report_value:
            issues.append(f"Risk Rejection Summary value mismatch: {field}")

    found_count, found_issue = parse_labeled_int(
        section, "Risk rejection fields found"
    )
    missing_count, missing_issue = parse_labeled_int(
        section, "Risk rejection fields missing"
    )
    if found_issue:
        issues.append(found_issue)
    if missing_issue:
        issues.append(missing_issue)

    actual_missing_fields = [
        field
        for field in RISK_REJECTION_FIELDS
        if actual_values.get(field) == "Not found"
    ]
    actual_found_count = len(RISK_REJECTION_FIELDS) - len(actual_missing_fields)

    if found_count is not None and found_count != actual_found_count:
        issues.append(
            f"Risk rejection found mismatch: expected {actual_found_count}, found {found_count}"
        )
    if missing_count is not None and missing_count != len(actual_missing_fields):
        issues.append(
            "Risk rejection missing mismatch: "
            f"expected {len(actual_missing_fields)}, found {missing_count}"
        )

    missing_mode, listed_fields = find_listed_risk_rejection_missing_fields(section)
    if not actual_missing_fields:
        if missing_mode != "none":
            issues.append("Risk rejection missing fields should be none")
        if listed_fields:
            issues.append("Risk rejection unexpected missing field list")
    else:
        if missing_mode == "none" or not listed_fields:
            issues.append("Risk rejection missing field list")

        actual_field_set = set(actual_missing_fields)
        listed_field_set = set(listed_fields)

        for field in listed_fields:
            if field not in RISK_REJECTION_FIELDS:
                issues.append(f"Unknown Risk Rejection missing field: {field}")

        for field in actual_missing_fields:
            if field not in listed_field_set:
                issues.append(f"Risk Rejection missing field: {field}")

        for field in listed_fields:
            if field in RISK_REJECTION_FIELDS and field not in actual_field_set:
                issues.append(f"Risk Rejection unexpected missing field: {field}")

    return issues


def find_log_throttle_issues(text):
    issues = []
    section = extract_section(text, "## Log Throttle Summary")
    if not section:
        return ["Log Throttle Summary section"]

    for required in (
        "Log throttle values are parsed from source text only.",
        "Not found log throttle fields are not inferred.",
        "Log throttle summary does not enable real trading.",
        "Log throttle ratios are reporting metrics, not trading signals.",
    ):
        if required not in section:
            issues.append(required)

    actual_values = {}
    for field in LOG_THROTTLE_FIELDS:
        report_value = parse_report_field_value(text, field)
        summary_value = parse_bullet_value(section, field)
        if summary_value is None:
            issues.append(f"Log Throttle Summary missing field: {field}")
            continue
        if report_value is None:
            issues.append(f"Runtime summary missing log throttle field: {field}")
            continue
        actual_values[field] = report_value
        if summary_value != report_value:
            issues.append(f"Log Throttle Summary value mismatch: {field}")

    found_count, found_issue = parse_labeled_int(
        section, "Log throttle fields found"
    )
    missing_count, missing_issue = parse_labeled_int(
        section, "Log throttle fields missing"
    )
    if found_issue:
        issues.append(found_issue)
    if missing_issue:
        issues.append(missing_issue)

    actual_missing_fields = [
        field
        for field in LOG_THROTTLE_FIELDS
        if actual_values.get(field) == "Not found"
    ]
    actual_found_count = len(LOG_THROTTLE_FIELDS) - len(actual_missing_fields)

    if found_count is not None and found_count != actual_found_count:
        issues.append(
            f"Log throttle found mismatch: expected {actual_found_count}, found {found_count}"
        )
    if missing_count is not None and missing_count != len(actual_missing_fields):
        issues.append(
            "Log throttle missing mismatch: "
            f"expected {len(actual_missing_fields)}, found {missing_count}"
        )

    printed_risk = parse_non_negative_int(actual_values.get("printedRiskRejectLogs"))
    suppressed_risk = parse_non_negative_int(
        actual_values.get("suppressedRiskRejectLogs")
    )
    risk_denominator = None
    if printed_risk is not None and suppressed_risk is not None:
        risk_denominator = printed_risk + suppressed_risk

    ratio_checks = [
        (
            "Risk reject log print ratio",
            expected_log_ratio(printed_risk, risk_denominator),
        ),
        (
            "New bar log print ratio",
            expected_log_ratio(
                parse_non_negative_int(actual_values.get("printedNewBarLogs")),
                parse_non_negative_int(actual_values.get("totalNewBarLogEvents")),
            ),
        ),
        (
            "Signal log print ratio",
            expected_log_ratio(
                parse_non_negative_int(actual_values.get("printedSignalLogs")),
                parse_non_negative_int(actual_values.get("totalSignalLogEvents")),
            ),
        ),
    ]

    for label, expected in ratio_checks:
        ratio, ratio_issue = parse_labeled_ratio(section, label)
        if ratio_issue:
            issues.append(ratio_issue)
            continue
        if ratio != expected:
            issues.append(
                f"{label} mismatch: expected {expected}, found {ratio}"
            )

    missing_mode, listed_fields = find_listed_log_throttle_missing_fields(section)
    if not actual_missing_fields:
        if missing_mode != "none":
            issues.append("Log throttle missing fields should be none")
        if listed_fields:
            issues.append("Log throttle unexpected missing field list")
    else:
        if missing_mode == "none" or not listed_fields:
            issues.append("Log throttle missing field list")

        actual_field_set = set(actual_missing_fields)
        listed_field_set = set(listed_fields)

        for field in listed_fields:
            if field not in LOG_THROTTLE_FIELDS:
                issues.append(f"Unknown Log Throttle missing field: {field}")

        for field in actual_missing_fields:
            if field not in listed_field_set:
                issues.append(f"Log Throttle missing field: {field}")

        for field in listed_fields:
            if field in LOG_THROTTLE_FIELDS and field not in actual_field_set:
                issues.append(f"Log Throttle unexpected missing field: {field}")

    return issues


def find_missing_field_notes_issues(text):
    issues = []
    notes = extract_section(text, "## Missing Field Notes")
    if not notes:
        return ["Missing Field Notes section"]

    not_found_fields = find_not_found_fields(text)
    listed_fields = find_listed_missing_fields(notes)
    reported_count, count_issue = parse_missing_fields_count(notes)
    actual_count = len(not_found_fields)

    if count_issue:
        issues.append(count_issue)
    elif reported_count != actual_count:
        issues.append(
            f"Missing fields count mismatch: expected {actual_count}, found {reported_count}"
        )

    if not_found_fields and not listed_fields:
        issues.append("Missing Field Notes listed field name")

    actual_field_set = set(not_found_fields)
    listed_field_set = set(listed_fields)

    for field in listed_fields:
        if field not in RUNTIME_SUMMARY_FIELDS:
            issues.append(f"Unknown Missing Field Notes field: {field}")

    for field in not_found_fields:
        if field not in listed_field_set:
            issues.append(f"Missing Field Notes missing field: {field}")

    for field in listed_fields:
        if field in RUNTIME_SUMMARY_FIELDS and field not in actual_field_set:
            issues.append(f"Missing Field Notes unexpected field: {field}")

    return issues


REQUIRED_FIELDS = [
    "totalTicks",
    "newBarsDetected",
    "signalsEvaluated",
    "riskRejected",
    "riskApproved",
    "executionAttempts",
    "buySignals",
    "sellSignals",
    "noneSignals",
    "signalDirectionChanges",
    "riskRejectSignalNone",
    "riskRejectTradingDisabled",
    "riskRejectInvalidPrice",
    "riskRejectSpreadTooHigh",
    "riskRejectTimeBlocked",
    "riskRejectMaxPositions",
    "riskRejectObservationMode",
    "totalRiskRejects",
    "printedRiskRejectLogs",
    "suppressedRiskRejectLogs",
    "totalNewBarLogEvents",
    "printedNewBarLogs",
    "suppressedNewBarLogs",
    "totalSignalLogEvents",
    "printedSignalLogs",
    "suppressedSignalLogs",
    "finalBalance",
]

RUNTIME_SUMMARY_FIELDS = [
    field for field in REQUIRED_FIELDS if field != "finalBalance"
]

SECTION_FIELDS = [
    ("Runtime Summary Counters", [
        "totalTicks",
        "newBarsDetected",
        "signalsEvaluated",
        "riskRejected",
        "riskApproved",
        "executionAttempts",
    ]),
    ("Runtime Summary Signal Stats", [
        "buySignals",
        "sellSignals",
        "noneSignals",
        "signalDirectionChanges",
    ]),
    ("Runtime Summary Risk Reject Stats", [
        "riskRejectSignalNone",
        "riskRejectTradingDisabled",
        "riskRejectInvalidPrice",
        "riskRejectSpreadTooHigh",
        "riskRejectTimeBlocked",
        "riskRejectMaxPositions",
        "riskRejectObservationMode",
        "totalRiskRejects",
    ]),
    ("Runtime Summary Risk Log Stats", [
        "printedRiskRejectLogs",
        "suppressedRiskRejectLogs",
    ]),
    ("Runtime Summary Core / New Bar Log Stats", [
        "totalNewBarLogEvents",
        "printedNewBarLogs",
        "suppressedNewBarLogs",
    ]),
    ("Runtime Summary Signal Log Stats", [
        "totalSignalLogEvents",
        "printedSignalLogs",
        "suppressedSignalLogs",
    ]),
    ("Final Balance", ["finalBalance"]),
]

SIGNAL_OBSERVATION_FIELDS = [
    "signalsEvaluated",
    "buySignals",
    "sellSignals",
    "noneSignals",
    "signalDirectionChanges",
]

RISK_REJECTION_FIELDS = [
    "riskRejected",
    "riskApproved",
    "totalRiskRejects",
    "riskRejectSignalNone",
    "riskRejectTradingDisabled",
    "riskRejectInvalidPrice",
    "riskRejectSpreadTooHigh",
    "riskRejectTimeBlocked",
    "riskRejectMaxPositions",
    "riskRejectObservationMode",
]

LOG_THROTTLE_FIELDS = [
    "printedRiskRejectLogs",
    "suppressedRiskRejectLogs",
    "totalNewBarLogEvents",
    "printedNewBarLogs",
    "suppressedNewBarLogs",
    "totalSignalLogEvents",
    "printedSignalLogs",
    "suppressedSignalLogs",
]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Validate a generated backtest runtime summary draft report."
    )
    parser.add_argument("--report", required=True, help="Generated Markdown report path.")
    return parser.parse_args()


def read_report(report_path):
    try:
        return report_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return report_path.read_text(encoding="utf-8-sig")


def find_missing_items(text):
    missing = []

    missing.extend(find_section_order_issues(text))
    missing.extend(find_prohibited_content_issues(text))

    for required in REQUIRED_SUBSTRINGS:
        if required not in text:
            missing.append(required)

    for field in REQUIRED_FIELDS:
        if field not in text:
            missing.append(field)

    missing.extend(find_missing_field_notes_issues(text))
    missing.extend(find_field_coverage_issues(text))
    missing.extend(find_signal_observation_issues(text))
    missing.extend(find_risk_rejection_issues(text))
    missing.extend(find_log_throttle_issues(text))

    return missing


def main():
    args = parse_args()
    report_path = Path(args.report)

    if not report_path.exists():
        print("Validation failed")
        print(f"Missing report file: {report_path}")
        return 1

    text = read_report(report_path)
    missing = find_missing_items(text)

    if missing:
        print("Validation failed")
        print(f"Report: {report_path}")
        print("Missing items:")
        for item in missing:
            print(f"- {item}")
        return 1

    print("Backtest runtime report validation passed")
    print("Validation passed")
    print(f"Report: {report_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
