//+------------------------------------------------------------------+
//|                                     WallStreet_Sniper_V5.mq5     |
//|                                  Generated by AI Quant Architect |
//|                     Version 5.0 - 修复时间切片悖论与底层黑匣子报警 |
//+------------------------------------------------------------------+
#property copyright "AI Quant Architect"
#property version   "5.00"

#include <Trade\Trade.mqh>

//--- 【核心风控模块】
input group "========== 核心风控模块 =========="
input int      Magic_Number         = 888888;           
input double   Risk_Percentage      = 1.0;              
input double   Min_Expectancy_Rate  = 0.2;              
input int      Max_Continuous_Loss  = 3;                
input double   Max_Daily_Drawdown   = 5.0;              
input double   Max_Single_Loss_Rate = 2.0;              

//--- 【复合信号提取模块】
input group "========== 复合信号提取模块 =========="
input int      BreakoutPeriod       = 20;               
input int      Trend_Filter_EMA     = 200;              
input bool     Enable_Entity_Break  = true;             
input int      ADXPeriod            = 14;               
input double   ADXThreshold         = 25.0;             
input int      GMT_Offset           = 0;                
input int      TradingStartHour     = 0;                // 为了测试，默认全天候
input int      TradingEndHour       = 24;               

//--- 【动态出场与保本模块】
input group "========== 动态出场与保本模块 =========="
input int      ATRPeriod            = 14;               
input double   ATRMultiplier        = 2.0;              
input bool     Enable_Break_Even    = true;             
input int      Break_Even_Slippage  = 5;                
input bool     Enable_Trailing_Stop = true;             
input double   TrailingATRMultiplier= 1.5;              

//--- 【恶劣环境过滤模块】
input group "========== 恶劣环境过滤模块 =========="
input int      MaxSpread            = 500;              // 为了测试，默认放宽
input bool     Enable_Weekend_Close = true;             
input bool     Enable_News_Filter   = false;            // 为了测试，默认关闭

//--- 【推送通知模块】
input group "========== 推送通知模块 =========="
input bool     Enable_Push          = false;             
input bool     Enable_Daily_Report  = false;             

//+------------------------------------------------------------------+
CTrade         Trade;
int            handle_ATR, handle_EMA, handle_ADX;
double         g_current_atr;                            
int            daily_loss_count;
double         daily_start_equity;
datetime       daily_reset_time;
double         cumulative_expectancy;
datetime       g_last_news_check_time;                   
bool           g_news_lock_flag;                         
bool           g_system_sleep;                           
datetime       g_last_report_time, g_last_bar_time;                          
int            g_daily_trades;                           
double         g_daily_pnl, g_total_win_amount, g_total_loss_amount;                       
int            g_total_win, g_total_loss, g_last_expectancy_deals;                  

//+------------------------------------------------------------------+
int OnInit()
{
   Trade.SetExpertMagicNumber(Magic_Number);
   Trade.SetDeviationInPoints(10);                       

   handle_ATR = iATR(_Symbol, PERIOD_CURRENT, ATRPeriod);
   handle_EMA = iMA(_Symbol, PERIOD_CURRENT, Trend_Filter_EMA, 0, MODE_EMA, PRICE_CLOSE);
   handle_ADX = iADX(_Symbol, PERIOD_CURRENT, ADXPeriod);

   if(handle_ATR == INVALID_HANDLE || handle_EMA == INVALID_HANDLE || handle_ADX == INVALID_HANDLE) return INIT_FAILED;
   
   daily_start_equity = AccountInfoDouble(ACCOUNT_EQUITY);
   Print("WallStreet_Sniper V5 部署成功！黑匣子监控已开启！");
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) { IndicatorRelease(handle_ATR); IndicatorRelease(handle_EMA); IndicatorRelease(handle_ADX); }

int GetTargetHour() { MqlDateTime dt; TimeCurrent(dt); return ((dt.hour + GMT_Offset) % 24 + 24) % 24; }

bool IsNewBar()
{
   datetime current_bar_time = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(current_bar_time == 0) return false;
   if(g_last_bar_time != current_bar_time) { g_last_bar_time = current_bar_time; return true; }
   return false;
}

//+------------------------------------------------------------------+
double CalculateSafeLotSize(double sl_points)
{
   double equity = AccountInfoDouble(ACCOUNT_EQUITY);
   double actual_risk_pct = fmin(Risk_Percentage, 2.0);
   double risk_amount = equity * (actual_risk_pct / 100.0);
   
   double tick_value = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tick_size = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);

   if(tick_value <= 0 || sl_points <= 0) return 0.0;
   double loss_per_lot = (sl_points * point / tick_size) * tick_value;
   if(loss_per_lot <= 0) return 0.0;

   double raw_lot = risk_amount / loss_per_lot;
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   raw_lot = MathFloor(raw_lot / step) * step;

   return fmax(SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN), fmin(raw_lot, SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX)));
}

bool CheckRiskRewardRatio(double entry, double sl, double tp)
{
   double risk = MathAbs(entry - sl), reward = MathAbs(tp - entry);
   return (risk > 0 && (reward / risk) >= 2.95); 
}

//+------------------------------------------------------------------+
void CheckBreakEvenAndTrailing()
{
   if(!Enable_Break_Even && !Enable_Trailing_Stop) return;
   if(g_current_atr <= 0.0) return;
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) != _Symbol || PositionGetInteger(POSITION_MAGIC) != Magic_Number) continue;

      double open_price = PositionGetDouble(POSITION_PRICE_OPEN);
      double current_sl = PositionGetDouble(POSITION_SL);
      double current_tp = PositionGetDouble(POSITION_TP);
      long type = PositionGetInteger(POSITION_TYPE);
      double current_price = (type == POSITION_TYPE_BUY) ? SymbolInfoDouble(_Symbol, SYMBOL_BID) : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      double profit_dist = MathAbs(current_price - open_price);

      if(profit_dist < g_current_atr) continue; 
      double be_sl = (type == POSITION_TYPE_BUY) ? open_price + Break_Even_Slippage * point : open_price - Break_Even_Slippage * point;

      if(Enable_Break_Even)
      {
         bool need_be = (type == POSITION_TYPE_BUY) ? (current_sl < be_sl && current_price > be_sl) : (current_sl > be_sl && current_price < be_sl);
         if(need_be && Trade.PositionModify(ticket, be_sl, current_tp)) current_sl = be_sl;
      }

      if(Enable_Trailing_Stop)
      {
         bool is_be_protected = (type == POSITION_TYPE_BUY) ? (current_sl >= be_sl - point) : (current_sl <= be_sl + point);
         if(!is_be_protected || MathAbs(current_price - be_sl) < g_current_atr * 0.5) continue;

         long stops_level = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
         double trailing_dist = g_current_atr * TrailingATRMultiplier;
         double new_trailing_sl = (type == POSITION_TYPE_BUY) ? current_price - trailing_dist : current_price + trailing_dist;

         if(stops_level > 0 && MathAbs(current_price - new_trailing_sl) < stops_level * point)
         {
            new_trailing_sl = (type == POSITION_TYPE_BUY) ? current_price - stops_level * point : current_price + stops_level * point;
         }

         if((type == POSITION_TYPE_BUY && new_trailing_sl < be_sl) || (type == POSITION_TYPE_SELL && new_trailing_sl > be_sl)) new_trailing_sl = be_sl;

         bool need_trail = (type == POSITION_TYPE_BUY) ? (new_trailing_sl > current_sl) : (new_trailing_sl < current_sl);
         if(need_trail) Trade.PositionModify(ticket, new_trailing_sl, current_tp);
      }
   }
}

//+------------------------------------------------------------------+
bool IsEnvironmentSafe()
{
   if(SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) > MaxSpread) 
   {
      // Print("拦截：点差过大 ", SymbolInfoInteger(_Symbol, SYMBOL_SPREAD));
      return false;
   }
   
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == Magic_Number) return false;
   }
   if(Enable_News_Filter && g_news_lock_flag) return false;
   return true;
}

//+------------------------------------------------------------------+
int CheckEntrySignal(double &current_atr)
{
   current_atr = 0.0;
   double atr_arr[], ema_arr[], adx_arr[];
   if(CopyBuffer(handle_ATR, 0, 1, 1, atr_arr) < 1 || CopyBuffer(handle_EMA, 0, 1, 1, ema_arr) < 1 || CopyBuffer(handle_ADX, 0, 1, 1, adx_arr) < 1) return 0;
   
   current_atr = atr_arr[0];
   if(current_atr <= 0 || adx_arr[0] < ADXThreshold) return 0;

   int target_hour = GetTargetHour();
   if(target_hour < TradingStartHour || target_hour >= TradingEndHour) return 0;

   // 🚨 核心修复：寻找极值必须跳过刚刚闭合的破局K线！从索引 2 开始寻找！
   int highest_idx = iHighest(_Symbol, PERIOD_CURRENT, MODE_HIGH, BreakoutPeriod, 2);
   int lowest_idx = iLowest(_Symbol, PERIOD_CURRENT, MODE_LOW, BreakoutPeriod, 2);
   if(highest_idx < 0 || lowest_idx < 0) return 0;

   double highest_high = iHigh(_Symbol, PERIOD_CURRENT, highest_idx);
   double lowest_low = iLow(_Symbol, PERIOD_CURRENT, lowest_idx);
   double last_close = iClose(_Symbol, PERIOD_CURRENT, 1);
   double last_open = iOpen(_Symbol, PERIOD_CURRENT, 1);

   if(last_close > highest_high && last_close > ema_arr[0] && (!Enable_Entity_Break || last_open > highest_high)) return 1;
   if(last_close < lowest_low && last_close < ema_arr[0] && (!Enable_Entity_Break || last_open < lowest_low)) return -1;
   return 0;
}

//+------------------------------------------------------------------+
void OnTick()
{
   if(g_system_sleep || !IsEnvironmentSafe() || !IsNewBar()) return;
   
   if(BarsCalculated(handle_ATR) < BreakoutPeriod || BarsCalculated(handle_EMA) < BreakoutPeriod) return;

   double current_atr = 0.0;
   int signal = CheckEntrySignal(current_atr);
   if(current_atr > 0) g_current_atr = current_atr;
   
   if(signal == 0) return;

   // 此时代表绝对出现了符合条件的信号！
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double entry = (signal == 1) ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double spread_cost = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD) * point;

   double sl = (signal == 1) ? entry - current_atr * ATRMultiplier - spread_cost : entry + current_atr * ATRMultiplier + spread_cost;
   double tp = (signal == 1) ? entry + MathAbs(entry - sl) * 3.0 : entry - MathAbs(entry - sl) * 3.0;

   long st_lvl = SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   if(st_lvl > 0 && MathAbs(entry - sl) < st_lvl * point)
   {
      sl = (signal == 1) ? entry - st_lvl * point : entry + st_lvl * point;
      tp = (signal == 1) ? entry + st_lvl * point * 3.0 : entry - st_lvl * point * 3.0;
   }

   if(!CheckRiskRewardRatio(entry, sl, tp))
   {
      Print("🔴 黑匣子拦截：盈亏比不足 3.0");
      return;
   }
   
   double lots = CalculateSafeLotSize(MathAbs(entry - sl) / point);
   if(lots <= 0)
   {
      Print("🔴 黑匣子拦截：手数计算异常 <= 0. (可能TickValue未加载)");
      return;
   }

   for(int retry = 0; retry < 3; retry++)
   {
      if((signal == 1 && Trade.Buy(lots, _Symbol, entry, sl, tp)) || (signal == -1 && Trade.Sell(lots, _Symbol, entry, sl, tp)))
      {
         Print("✅ 狙击手开火成功！方向: ", (signal == 1 ? "多" : "空"), " 手数: ", lots);
         break;
      }
      else
      {
         Print("❌ 开火失败，错误码: ", GetLastError());
         Sleep(100);
      }
   }
}
//+------------------------------------------------------------------+